# Crawling PTA

In [ ]:
!pip install requests
!pip install beautifulsoup4
import requests
from bs4 import BeautifulSoup
import pandas as pd

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2025.8.3)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (4.13.5)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (4.15.0)

4. **Teknik**

Teknik Industri

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def Industri():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": [],
        "prodi" : []
    }

    for i in range(1, 144):
        print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/9/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)
            data["prodi"].append("Teknik Industri")

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("Industri.csv", index=False)

    return df

In [ ]:
Industri()

📄 Memproses halaman ke-1
📄 Memproses halaman ke-2
📄 Memproses halaman ke-3
📄 Memproses halaman ke-4
📄 Memproses halaman ke-5
📄 Memproses halaman ke-6
📄 Memproses halaman ke-7
📄 Memproses halaman ke-8
📄 Memproses halaman ke-9
📄 Memproses halaman ke-10
📄 Memproses halaman ke-11
📄 Memproses halaman ke-12
📄 Memproses halaman ke-13
📄 Memproses halaman ke-14
📄 Memproses halaman ke-15
📄 Memproses halaman ke-16
📄 Memproses halaman ke-17
📄 Memproses halaman ke-18
📄 Memproses halaman ke-19
📄 Memproses halaman ke-20
📄 Memproses halaman ke-21
📄 Memproses halaman ke-22
📄 Memproses halaman ke-23
📄 Memproses halaman ke-24
📄 Memproses halaman ke-25
📄 Memproses halaman ke-26
📄 Memproses halaman ke-27
📄 Memproses halaman ke-28
📄 Memproses halaman ke-29
📄 Memproses halaman ke-30
📄 Memproses halaman ke-31
📄 Memproses halaman ke-32
📄 Memproses halaman ke-33
📄 Memproses halaman ke-34
📄 Memproses halaman ke-35
📄 Memproses halaman ke-36
📄 Memproses halaman ke-37
📄 Memproses halaman ke-38
📄 Memproses halaman ke-39
📄 Memproses halaman ke-40
📄 Memproses halaman ke-41
📄 Memproses halaman ke-42
📄 Memproses halaman ke-43
📄 Memproses halaman ke-44
📄 Memproses halaman ke-45
📄 Memproses halaman ke-46
📄 Memproses halaman ke-47
📄 Memproses halaman ke-48
📄 Memproses halaman ke-49
📄 Memproses halaman ke-50
📄 Memproses halaman ke-51
📄 Memproses halaman ke-52
📄 Memproses halaman ke-53
📄 Memproses halaman ke-54
📄 Memproses halaman ke-55
📄 Memproses halaman ke-56
📄 Memproses halaman ke-57
📄 Memproses halaman ke-58
📄 Memproses halaman ke-59
📄 Memproses halaman ke-60
📄 Memproses halaman ke-61
📄 Memproses halaman ke-62
📄 Memproses halaman ke-63
📄 Memproses halaman ke-64
📄 Memproses halaman ke-65
📄 Memproses halaman ke-66
📄 Memproses halaman ke-67
📄 Memproses halaman ke-68
📄 Memproses halaman ke-69
📄 Memproses halaman ke-70
📄 Memproses halaman ke-71
📄 Memproses halaman ke-72
📄 Memproses halaman ke-73
📄 Memproses halaman ke-74
📄 Memproses halaman ke-75
📄 Memproses halaman ke-76
📄 Memproses halaman ke-77
📄 Memproses halaman ke-78
📄 Memproses halaman ke-79
📄 Memproses halaman ke-80
📄 Memproses halaman ke-81
📄 Memproses halaman ke-82
📄 Memproses halaman ke-83
📄 Memproses halaman ke-84
📄 Memproses halaman ke-85
📄 Memproses halaman ke-86
📄 Memproses halaman ke-87
📄 Memproses halaman ke-88
📄 Memproses halaman ke-89
📄 Memproses halaman ke-90
📄 Memproses halaman ke-91
📄 Memproses halaman ke-92
📄 Memproses halaman ke-93
📄 Memproses halaman ke-94
📄 Memproses halaman ke-95
📄 Memproses halaman ke-96
📄 Memproses halaman ke-97
📄 Memproses halaman ke-98
📄 Memproses halaman ke-99
📄 Memproses halaman ke-100
📄 Memproses halaman ke-101
📄 Memproses halaman ke-102
📄 Memproses halaman ke-103
📄 Memproses halaman ke-104
📄 Memproses halaman ke-105
📄 Memproses halaman ke-106
📄 Memproses halaman ke-107
📄 Memproses halaman ke-108
📄 Memproses halaman ke-109
📄 Memproses halaman ke-110
📄 Memproses halaman ke-111
📄 Memproses halaman ke-112
📄 Memproses halaman ke-113
📄 Memproses halaman ke-114
📄 Memproses halaman ke-115
📄 Memproses halaman ke-116
📄 Memproses halaman ke-117
📄 Memproses halaman ke-118
📄 Memproses halaman ke-119
📄 Memproses halaman ke-120
📄 Memproses halaman ke-121
📄 Memproses halaman ke-122
📄 Memproses halaman ke-123
📄 Memproses halaman ke-124
📄 Memproses halaman ke-125
📄 Memproses halaman ke-126
📄 Memproses halaman ke-127
📄 Memproses halaman ke-128
📄 Memproses halaman ke-129
📄 Memproses halaman ke-130
📄 Memproses halaman ke-131
📄 Memproses halaman ke-132
📄 Memproses halaman ke-133
📄 Memproses halaman ke-134
📄 Memproses halaman ke-135
📄 Memproses halaman ke-136
📄 Memproses halaman ke-137
📄 Memproses halaman ke-138
📄 Memproses halaman ke-139
📄 Memproses halaman ke-140
📄 Memproses halaman ke-141
📄 Memproses halaman ke-142
📄 Memproses halaman ke-143

,penulis,judul,pembimbing_pertama,pembimbing_kedua,abstrak_indo,abstrak_inggris,prodi
0,Siliwangi Fitra Rachmawanto S.T.,OPTIMASI PEMILIHAN PORTOFOLIO SAHAM PERUSAHAAN...,"Heri Awalul Ilhamsah S.T., M.T.","Retno Indriartiningtias S.T., M.T.",Portofolio adalah sekumpulan saham yang dimili...,Portofolio is a collection of stock owned by i...,Teknik Industri
1,AHMAD MAS'UD,PERANCANGAN TATA LETAK FASILITAS LANTAI PRODUK...,"SABARUDIN AKHMAD, S.T., M.T.","SUGENG PURWOKO, S.T., M.T.",PT. ABC merupakan perusahaan yang bergerak dib...,PT. ABC is a company engaged in the manufactur...,Teknik Industri
2,Yulianto Fauzanta,PERUMUSAN STRATEGI BISNIS UD. BUDI JAYA BANGKA...,"Fitri Agustina, S.T., M.T","Retno Indriartiningtias, S.T., M.T",Bangkalan merupakan salah satu kabupaten yang ...,Bangkalan is one of the districts that have th...,Teknik Industri
3,M Mundir Muhlisin,USULAN PERBAIKAN UTILITAS RESOURCES PADA LANTA...,Mu'alim ST MT,Sugeng Purwoko ST MT,Simulasi adalah duplikasi atau abstraksi dari ...,Simulation is a duplication or abstraction of ...,Teknik Industri
4,Muhibbin,Peningkatan Kepuasan Masyarakat Terhadap Pelay...,Rahmad Hidayat,Retno Indriartiningtias,Kepuasan adalah tingkat perasaan seseorang ter...,Satisfaction is feeling level of someone to se...,Teknik Industri
...,...,...,...,...,...,...,...
706,YOLANDA ABIGAIL LAPIAN,USULAN PERBAIKAN UPAYA MINIMASI REJECT PART BO...,"Prof. Dr. Rachmad Hidayat, M.T.,IPU, Asean Eng","Imron Kuswandi S.T., M.T",Kualitas dan pengendalian kualitas memiliki pe...,Quality and quality control have an important ...,Teknik Industri
707,Nisfu Laylatus Sabihis,PERENCANAAN KEBIJAKAN PENGENDALIAN PERSEDIAAN ...,"Sugeng Purwoko, S.T., M.T","Mu'alim, S.T., M.T",PT. Apie Indo Karunia merupakan suatu perusaha...,PT. Apie Indo Karunia is a company in the man...,Teknik Industri
708,Muhammad Asri Wahyu Dianto,PENGEMBANGAN DAN KARAKTERISASI HASIL ASSESSMEN...,"Dr.Sabarudin Akhmad, S.T., M.T., IPM. Asean Eng","Anis Arendra S.T,. M.Eng",MSDs atau Musculoskeletal Disorders adalah gan...,MSDs or Musculoskeletal Disorders are injuries...,Teknik Industri
709,MUNIF SAYID ANWAS PRABOWO,Evaluasi Tingkat Kelelahan Kerja Perawat Ruang...,"Dr. Weny Findiastuti, S.T.,M.T","Rullie Annisa, S.T.,M.T",Rumah sakit merupakan salah satu instansi di b...,The hospital is one of the institutions in the...,Teknik Industri
710,Lilis Kurnia Ikamawati,PENENTUAN TINGKAT PRIORITAS PERBAIKAN MODE KEG...,"Dr. Kukuh Winarso, S.Si., M.T, IPM. Asean Eng","Issa Dyah Utami, S.T., M.T.",Penelitian ini berlokasikan di PT Semen Indone...,This research is located at PT Semen Indonesia...,Teknik Industri

Teknik Informatika

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def Infor():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": [],
        "prodi" : []
    }

    for i in range(1, 173):
        print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/10/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)
            data["prodi"].append("Teknik Informatika")

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("Infor.csv", index=False)

    return df

In [ ]:
Infor()

📄 Memproses halaman ke-1
📄 Memproses halaman ke-2
📄 Memproses halaman ke-3
📄 Memproses halaman ke-4
📄 Memproses halaman ke-5
📄 Memproses halaman ke-6
📄 Memproses halaman ke-7
📄 Memproses halaman ke-8
📄 Memproses halaman ke-9
📄 Memproses halaman ke-10
📄 Memproses halaman ke-11
📄 Memproses halaman ke-12
📄 Memproses halaman ke-13
📄 Memproses halaman ke-14
📄 Memproses halaman ke-15
📄 Memproses halaman ke-16
📄 Memproses halaman ke-17
📄 Memproses halaman ke-18
📄 Memproses halaman ke-19
📄 Memproses halaman ke-20
📄 Memproses halaman ke-21
📄 Memproses halaman ke-22
📄 Memproses halaman ke-23
📄 Memproses halaman ke-24
📄 Memproses halaman ke-25
📄 Memproses halaman ke-26
📄 Memproses halaman ke-27
📄 Memproses halaman ke-28
📄 Memproses halaman ke-29
📄 Memproses halaman ke-30
📄 Memproses halaman ke-31
📄 Memproses halaman ke-32
📄 Memproses halaman ke-33
📄 Memproses halaman ke-34
📄 Memproses halaman ke-35
📄 Memproses halaman ke-36
📄 Memproses halaman ke-37
📄 Memproses halaman ke-38
📄 Memproses halaman ke-39
📄 Memproses halaman ke-40
📄 Memproses halaman ke-41
📄 Memproses halaman ke-42
📄 Memproses halaman ke-43
📄 Memproses halaman ke-44
📄 Memproses halaman ke-45
📄 Memproses halaman ke-46
📄 Memproses halaman ke-47
📄 Memproses halaman ke-48
📄 Memproses halaman ke-49
📄 Memproses halaman ke-50
📄 Memproses halaman ke-51
📄 Memproses halaman ke-52
📄 Memproses halaman ke-53
📄 Memproses halaman ke-54
📄 Memproses halaman ke-55
📄 Memproses halaman ke-56
📄 Memproses halaman ke-57
📄 Memproses halaman ke-58
📄 Memproses halaman ke-59
📄 Memproses halaman ke-60
📄 Memproses halaman ke-61
📄 Memproses halaman ke-62
📄 Memproses halaman ke-63
📄 Memproses halaman ke-64
📄 Memproses halaman ke-65
📄 Memproses halaman ke-66
📄 Memproses halaman ke-67
📄 Memproses halaman ke-68
📄 Memproses halaman ke-69
📄 Memproses halaman ke-70
📄 Memproses halaman ke-71
📄 Memproses halaman ke-72
📄 Memproses halaman ke-73
📄 Memproses halaman ke-74
📄 Memproses halaman ke-75
📄 Memproses halaman ke-76
📄 Memproses halaman ke-77
📄 Memproses halaman ke-78
📄 Memproses halaman ke-79
📄 Memproses halaman ke-80
📄 Memproses halaman ke-81
📄 Memproses halaman ke-82
📄 Memproses halaman ke-83
📄 Memproses halaman ke-84
📄 Memproses halaman ke-85
📄 Memproses halaman ke-86
📄 Memproses halaman ke-87
📄 Memproses halaman ke-88
📄 Memproses halaman ke-89
📄 Memproses halaman ke-90
📄 Memproses halaman ke-91
📄 Memproses halaman ke-92
📄 Memproses halaman ke-93
📄 Memproses halaman ke-94
📄 Memproses halaman ke-95
📄 Memproses halaman ke-96
📄 Memproses halaman ke-97
📄 Memproses halaman ke-98
📄 Memproses halaman ke-99
📄 Memproses halaman ke-100
📄 Memproses halaman ke-101
📄 Memproses halaman ke-102
📄 Memproses halaman ke-103
📄 Memproses halaman ke-104
📄 Memproses halaman ke-105
📄 Memproses halaman ke-106
📄 Memproses halaman ke-107
📄 Memproses halaman ke-108
📄 Memproses halaman ke-109
📄 Memproses halaman ke-110
📄 Memproses halaman ke-111
📄 Memproses halaman ke-112
📄 Memproses halaman ke-113
📄 Memproses halaman ke-114
📄 Memproses halaman ke-115
📄 Memproses halaman ke-116
📄 Memproses halaman ke-117
📄 Memproses halaman ke-118
📄 Memproses halaman ke-119
📄 Memproses halaman ke-120
📄 Memproses halaman ke-121
📄 Memproses halaman ke-122
📄 Memproses halaman ke-123
📄 Memproses halaman ke-124
📄 Memproses halaman ke-125
📄 Memproses halaman ke-126
📄 Memproses halaman ke-127
📄 Memproses halaman ke-128
📄 Memproses halaman ke-129
📄 Memproses halaman ke-130
📄 Memproses halaman ke-131
📄 Memproses halaman ke-132
📄 Memproses halaman ke-133
📄 Memproses halaman ke-134
📄 Memproses halaman ke-135
📄 Memproses halaman ke-136
📄 Memproses halaman ke-137
📄 Memproses halaman ke-138
📄 Memproses halaman ke-139
📄 Memproses halaman ke-140
📄 Memproses halaman ke-141
📄 Memproses halaman ke-142
📄 Memproses halaman ke-143
📄 Memproses halaman ke-144
📄 Memproses halaman ke-145
📄 Memproses halaman ke-146
📄 Memproses halaman ke-147
📄 Memproses halaman ke-148
📄 Memproses halaman ke-149
📄 Memproses halaman ke-150
📄 Memproses halaman ke-151
📄 Memproses halaman ke-152
📄 Memproses halaman ke-153
📄 Memproses halaman ke-154
📄 Memproses halaman ke-155
📄 Memproses halaman ke-156
📄 Memproses halaman ke-157
📄 Memproses halaman ke-158
📄 Memproses halaman ke-159
📄 Memproses halaman ke-160
📄 Memproses halaman ke-161
📄 Memproses halaman ke-162
📄 Memproses halaman ke-163
📄 Memproses halaman ke-164
📄 Memproses halaman ke-165
📄 Memproses halaman ke-166
📄 Memproses halaman ke-167
📄 Memproses halaman ke-168
📄 Memproses halaman ke-169
📄 Memproses halaman ke-170
📄 Memproses halaman ke-171
📄 Memproses halaman ke-172

,penulis,judul,pembimbing_pertama,pembimbing_kedua,abstrak_indo,abstrak_inggris,prodi
0,A.Ubaidillah S.Kom,PERANCANGAN DAN IMPLEMENTASI SISTEM DATABASE \...,Budi Setyono M.T,Hermawan S.T,Sistem informasi akademik (SIAKAD) merupaka...,Academic information systems (SIAKAD) is an in...,Teknik Informatika
1,"M. Basith Ardianto,",APLIKASI KONTROL DAN MONITORING JARINGAN KOMPU...,"Drs. Budi Soesilo, MT","Koko Joni, ST",Berjalannya koneksi jaringan komputer dengan l...,-,Teknik Informatika
2,"Akhmad Suyandi, S.Kom",RANCANG BANGUN APLIKASI PROXY SERVER UNTUK\r\n...,"Drs. Budi Soesilo, M.T","Hermawan, ST, MT",Web server adalah sebuah perangkat lunak serve...,Web server is a server software functioning to...,Teknik Informatika
3,Heri Supriyanto,SISTEM PENDUKUNG KEPUTUSAN OPTIMASI PENJADWALA...,"Mulaab, S.Si., M.Kom","Firli Irhamni, ST., M.Kom",Penjadwalan kuliah di Perguruan Tinggi me...,Scheduling courses in universities is a ...,Teknik Informatika
4,Septian Rahman Hakim,SISTEM AUGMENTED REALITY ANIMASI BENDA BERGERA...,"Arik Kurniawati, S.Kom., M.T.","Haryanto, S.T., M.T.",Seiring perkembangan teknologi yang ada diduni...,As the development of technology existing in t...,Teknik Informatika
...,...,...,...,...,...,...,...
853,Rachmad Agung Pambudi,PENERAPAN ALGORITMA LONG-SHORT TERM MEMORY UNT...,"Eka Mala Sari Rochman, S.Kom., M.Kom","Sri Herawati, S.Kom., M.Kom",Investasi saham selama ini memiliki resiko ker...,Investment in shares so far has a very large r...,Teknik Informatika
854,Nadila Hidayanti,SISTEM PENCARIAN TEKS AL-QURAN TERJEMAHAN BERB...,"Achmad Jauhari, S.T., M.Kom","Ika Oktavia Suzanti, S.Kom., M.Cs",Information Retrieval (IR) merupakan pengambil...,Information Retrieval (IR) is retrieval of inf...,Teknik Informatika
855,Afni Sakinah,KLASIFIKASI KOMPLEKSITAS VISUAL CITRA SAMPAH M...,"Dr. Indah Agustien Siradjuddin, S.Kom., M.Kom.","Moch. Kautsar Sophan, S.Kom., M.MT.",Klasifikasi citra merupakan proses pengelompok...,Image classification is a process of grouping ...,Teknik Informatika
856,Friska Fatmawatiningrum,IDENTIFIKASI BINER ATRIBUT PEJALAN KAKI MENGGU...,"Dr. Indah Agustien Siradjuddin, S.Kom., M.Kom.","Prof. Dr. Arief Muntasa, S.Si., M.MT.",Identifikasi atribut pejalan kaki merupakan sa...,The identification of pedestrian attributes is...,Teknik Informatika
857,Dian Wibowo,DETEKSI OBJEK MANUSIA BERBASIS ONE STAGE DETEC...,"Dr. Indah Agustien Siradjuddin, S.Kom., M.Kom.","Moch. Kautsar Sophan, S.Kom., M.MT.",Topik deteksi objek telah menarik perhatian ya...,The topic of object detection has attracted gr...,Teknik Informatika

Manajemen Informatika

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def Minfor():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": [],
        "prodi" : []
    }

    for i in range(1, 57):
        print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/11/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)
            data["prodi"].append("Manajemen Informatika")

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("Minfor.csv", index=False)

    return df

In [ ]:
Minfor()

📄 Memproses halaman ke-1
📄 Memproses halaman ke-2
📄 Memproses halaman ke-3
📄 Memproses halaman ke-4
📄 Memproses halaman ke-5
📄 Memproses halaman ke-6
📄 Memproses halaman ke-7
📄 Memproses halaman ke-8
📄 Memproses halaman ke-9
📄 Memproses halaman ke-10
📄 Memproses halaman ke-11
📄 Memproses halaman ke-12
📄 Memproses halaman ke-13
📄 Memproses halaman ke-14
📄 Memproses halaman ke-15
📄 Memproses halaman ke-16
📄 Memproses halaman ke-17
📄 Memproses halaman ke-18
📄 Memproses halaman ke-19
📄 Memproses halaman ke-20
📄 Memproses halaman ke-21
📄 Memproses halaman ke-22
📄 Memproses halaman ke-23
📄 Memproses halaman ke-24
📄 Memproses halaman ke-25
📄 Memproses halaman ke-26
📄 Memproses halaman ke-27
📄 Memproses halaman ke-28
📄 Memproses halaman ke-29
📄 Memproses halaman ke-30
📄 Memproses halaman ke-31
📄 Memproses halaman ke-32
📄 Memproses halaman ke-33
📄 Memproses halaman ke-34
📄 Memproses halaman ke-35
📄 Memproses halaman ke-36
📄 Memproses halaman ke-37
📄 Memproses halaman ke-38
📄 Memproses halaman ke-39
📄 Memproses halaman ke-40
📄 Memproses halaman ke-41
📄 Memproses halaman ke-42
📄 Memproses halaman ke-43
📄 Memproses halaman ke-44
📄 Memproses halaman ke-45
📄 Memproses halaman ke-46
📄 Memproses halaman ke-47
📄 Memproses halaman ke-48
📄 Memproses halaman ke-49
📄 Memproses halaman ke-50
📄 Memproses halaman ke-51
📄 Memproses halaman ke-52
📄 Memproses halaman ke-53
📄 Memproses halaman ke-54
📄 Memproses halaman ke-55
📄 Memproses halaman ke-56

,penulis,judul,pembimbing_pertama,pembimbing_kedua,abstrak_indo,abstrak_inggris,prodi
0,Elky Lilik Misdayani,SISTEM INFORMASI PERUSAHAAN OTOBUS SUMBER KENC...,"Fitri Damayanti,S.Kom,M.Kom",,Sistem informasi pengolahan data yang dibutuhk...,Data processing information systems needed by ...,Manajemen Informatika
1,lu'luul maknun,SISTEM INFORMASI GEOGRAFIS PEMETAAN POTENSI OB...,"Aeri Rahmad,S.T,M.T",-,Abstrak\r\nPerkembangan teknologi di berbagai ...,Abstract\r\nData processing systems required b...,Manajemen Informatika
2,Megawati Bukhori Putri,SISTEM INFORMASI PSIKOTES BERBASIS DEKSTOP,"Yeni Kustianingsih, S.Kom, M.Kom",-,Abstrak\r\nPerkembangan teknologi di berbagai ...,Abstract\r\nTechnological developments in vari...,Manajemen Informatika
3,Andika Syarifuddin Parmana Putra,Perancangan Dan Pembuatan Sistem Informasi Man...,"Sri Herawati,S.Kom","Sri Herawati,S.Kom",Abstrak\r\n\r\nSistem Informasi Manajemen Data...,Abstract\r\n\r\nData Management Information Sy...,Manajemen Informatika
4,Deka Pranaristanto,SISTEM INFORMASI PEMESANAN RUMAH BERBASIS WEB ...,"Budi Dwi Satoto S.T, M.Kom","Budi Dwi Satoto S.T, M.Kom",Sistem pemesanan atau profil tentang PT. PROPI...,Ordering system or the profile of PT. MAIN WIR...,Manajemen Informatika
...,...,...,...,...,...,...,...
275,MAKBUL ZAKARIYA,APLIKASI PEMESANAN SIRKUIT LINTASAN BALAP BERB...,"FITRI DAMAYANTI, S.KOM., M.KOM",,Masyarakat harus datang terlebih dahulu untuk ...,The public must come first to order the race t...,Manajemen Informatika
276,Tri Nanda Irawan,SISTEM MONITORING PENILAIAN KINERJA PEGAWAI\nP...,"Novi Prastiti, S.Kom., M.Kom",,Pengertian Penilaian kinerja pegawai adalah su...,Understanding Employee appraisal is a structur...,Manajemen Informatika
277,Satrio Suwantoro,Penerapan Metode clustering dengan\n k – means...,"Novi Prastiti. S.kom,. M.kom.",,Kabupaten Bangkalan merupakan salah satu kabup...,Bangkalan is one of the districts that have ma...,Manajemen Informatika
278,Miftahor Rahman,SISTEM INFORMASI GEOGRAFIS PELAYANAN KESEHATAN...,"Novi Prastiti, S.Kom., M.Kom",,Pelayanan sebagai proses pemenuhan kebutuhan m...,Service as a process of fulfilling needs throu...,Manajemen Informatika
279,Moh Ilham Ramdhan Fajrin,SISTEM PAKAR DIAGNOSA PENYAKIT MATA DENGAN MEN...,"Mohammad Syarief, S.T,. M.Cs.","Mohammad Syarief, S.T,. M.Cs.",ABSTRAK\n\nMata merupakan salah satu dari panc...,ABSTRACT The eye is one of the five senses whi...,Manajemen Informatika

Teknik Multimedia dan Jaringan

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def Multijaringan():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": [],
        "prodi" : []
    }

    for i in range(1, 28):
        print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/19/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)
            data["prodi"].append("Teknik Multimedia dan Jaringan")

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("Multijaringan().csv", index=False)

    return df

In [ ]:
Multijaringan()

📄 Memproses halaman ke-1
📄 Memproses halaman ke-2
📄 Memproses halaman ke-3
📄 Memproses halaman ke-4
📄 Memproses halaman ke-5
📄 Memproses halaman ke-6
📄 Memproses halaman ke-7
📄 Memproses halaman ke-8
📄 Memproses halaman ke-9
📄 Memproses halaman ke-10
📄 Memproses halaman ke-11
📄 Memproses halaman ke-12
📄 Memproses halaman ke-13
📄 Memproses halaman ke-14
📄 Memproses halaman ke-15
📄 Memproses halaman ke-16
📄 Memproses halaman ke-17
📄 Memproses halaman ke-18
📄 Memproses halaman ke-19
📄 Memproses halaman ke-20
📄 Memproses halaman ke-21
📄 Memproses halaman ke-22
📄 Memproses halaman ke-23
📄 Memproses halaman ke-24
📄 Memproses halaman ke-25
📄 Memproses halaman ke-26
📄 Memproses halaman ke-27

,penulis,judul,pembimbing_pertama,pembimbing_kedua,abstrak_indo,abstrak_inggris,prodi
0,Achmad Husaini,Elektronik Pemilihan Kepala Desa Menggunakan M...,"Aeri Rachmad, ST. MT.",,ABSTRAK\r\n\r\nPerkembangan teknologi informas...,ABSTRACT\r\n\r\nThe development of information...,Teknik Multimedia dan Jaringan
1,FIKRI MUJADDIDI ALHAK,DIGITAL INFORMATION ASSISTANT,"AERI RACHMAD, ST., MT",,Media informasi kini perkembangannya sangat pe...,Media information is now very rapid developmen...,Teknik Multimedia dan Jaringan
2,artika frida nirmala,perancangan aplikasi female e-healthy untuk de...,"Aeri Rachmad ST, MT",,Kanker serviks merupakan kanker terganas yang ...,Cervical cancer is a vicious cancer caused by ...,Teknik Multimedia dan Jaringan
3,Ahmad Rivai,SISTEM INFORMASI TUGAS AKHIR PRODI TEKNIK MULT...,"Riza Alfita. S.T.,M.T.",-,Prodi teknik Multimedia dan Jaringan adalah sa...,Multimedia and Network engineering is one of t...,Teknik Multimedia dan Jaringan
4,Idrus Tamam,APLIKASI PETA WISATA DIGITAL BANGKALAN DENGAN\...,"Aeri Rachmad, S.T.,M. T",,Pemerintah Indonesia telah berupaya meningkatk...,The Indonesian government has worked to increa...,Teknik Multimedia dan Jaringan
...,...,...,...,...,...,...,...
126,Aunur Rofiq,APLIKASI SISTEM PENDUKUNG KEPUTUSAN TERHADAP P...,"M. Ali Syakur, S.Si., M.T.",,Penyakit THT (Telinga Hidung dan Tenggorokan) ...,ENT disease (Ear Nose and Throat) is a disease...,Teknik Multimedia dan Jaringan
127,Rehadian Teja Sukmana Putra,Sistem Informasi Pangkalan Data Garam di Pulau...,"Ach. Khozaimi, S.Kom., M.Kom",,Garam merupakan salah satu komoditi besar Indo...,Salt is one of Indonesia's major commodities. ...,Teknik Multimedia dan Jaringan
128,Ginanjar Eka Poetra,RANCANG BANGUN SISTEM INFORMASI KEUANGAN “DEP...,"M. Ali Syakur, S.Si., M.T",,Proses perkembangan sebuah usaha tidak akan le...,The process of development of a business will ...,Teknik Multimedia dan Jaringan
129,Rizky wara setyawan,RANCANG BANGUN APLIKASI DIAGNOSIS PENYAKIT SAP...,Devie Rosa Amanisa,,Peternak sapi sering mengalami kesulitan dala...,Cattle ranchers often have difficulty in findi...,Teknik Multimedia dan Jaringan
130,Muhammad Siswandi,Sistem Pakar Diagnosis Penyakit Unggas Menggun...,"Devie Rosa Anamisa. S.Kom., M.Kom",,Unggas adalah jenis hewan ternak kelompok bur...,Poultry is a type of livestock bird group that...,Teknik Multimedia dan Jaringan

Mekatronika

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def Mekatro():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": [],
        "prodi" : []
    }

    for i in range(1, 29):
        print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/20/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)
            data["prodi"].append("Mekatro")

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("Mekatro.csv", index=False)

    return df

In [ ]:
Mekatro()

📄 Memproses halaman ke-1
📄 Memproses halaman ke-2
📄 Memproses halaman ke-3
📄 Memproses halaman ke-4
📄 Memproses halaman ke-5
📄 Memproses halaman ke-6
📄 Memproses halaman ke-7
📄 Memproses halaman ke-8
📄 Memproses halaman ke-9
📄 Memproses halaman ke-10
📄 Memproses halaman ke-11
📄 Memproses halaman ke-12
📄 Memproses halaman ke-13
📄 Memproses halaman ke-14
📄 Memproses halaman ke-15
📄 Memproses halaman ke-16
📄 Memproses halaman ke-17
📄 Memproses halaman ke-18
📄 Memproses halaman ke-19
📄 Memproses halaman ke-20
📄 Memproses halaman ke-21
📄 Memproses halaman ke-22
📄 Memproses halaman ke-23
📄 Memproses halaman ke-24
📄 Memproses halaman ke-25
📄 Memproses halaman ke-26
📄 Memproses halaman ke-27
📄 Memproses halaman ke-28

,penulis,judul,pembimbing_pertama,pembimbing_kedua,abstrak_indo,abstrak_inggris,prodi
0,Moh. Amin Wahyudi,PERANCANGAN INJECTOR CLEANER DAN TESTER PADA S...,"Hairil Budiarto, S.T., MT.",,ABSTRAK\r\nSepeda motor menggunakan sistem inj...,ABSTRACT\r\nMotorcycle injection system is cur...,Mekatro
1,DWI NUGROHO,PROTOTYPE ALAT PEMBERI PAKAN\r\nAYAM PETELUR O...,"Muhammad Fuad, S.Kom. , MT.","Mirza Pramudia, ST. , M.Eng.",Peternakan merupakan salah satu bidang usaha y...,Livestock is one of the promising areas of bus...,Mekatro
2,Rezky Septian Akbar,pengukur tinggi badan berbasis arduino,"Ahmad Sahru Romadhon, S.Kom., M.T.",,Perkembangan ilmu pengetahuan teknologi yang m...,The development of modern technology science h...,Mekatro
3,Rio Tri Susanto,PEMODELAN SISTEM INFORMASI KETERSEDIAAN RUANG ...,"Muhammad Latif, S.T., M.T",,Pengaturan parkir yang sampai saat ini masih b...,Mostly parking arrangement was done manually u...,Mekatro
4,Moh. Iswahyudinorrahman,Desain Sistem pengendali Pintu otomatis Menggu...,"ahmad Sahru Romadhon, S.KOM., M.T.",,Pada zaman globalisasi mendorong teknologi unt...,At globalization epoch push technology to rapi...,Mekatro
...,...,...,...,...,...,...,...
132,Agus Dian Prayana,JAM BERBICARA UNTUK TUNA NETRA,"SRI WAHYUNI,S.KOM.M.T",,Indera penglihatan adalah salah satu sumber in...,The senses of detection are one of the main in...,Mekatro
133,Rifki Masfuddin,Alat daur ulang kertas menjadi bubur kertas (p...,"Vivi Tri Widyaningrum, S.Kom., M.T.",,Daur ulang limbah kertas adalah proses untuk m...,Waste paper recycling is a process to utilize ...,Mekatro
134,Yudiono,Alat Penyiram Bawang Merah Otomatis Untuk Meng...,"Sri Wahyuni, S.Kom, M.T.",,Bawang merah merupakan sayuran rempah yang cuk...,Shallots are spice vegetables that are quite p...,Mekatro
135,Jundullah Abdul Aziz M.,PROTOTIPE KONVEYOR BERBASIS METAL DETEKSI MAGN...,"Sri Wahyuni, S.Kom., M.T",,Keunggulan dalam bidang teknologi di era moder...,Excellence in the field of technology in the m...,Mekatro
136,Satria Jaya Rizaldy,PROTOTYPE PEMERIKSA BUTA WARNA,"Hairil Budiarto., S.T., M.T",,ABSTRAK\n\nPenelitian ini bertujuan untuk memb...,ABSTRACT\n\nThis study aims to build a color b...,Mekatro

Teknik Elektro

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def Elektro():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": [],
        "prodi" : []
    }

    for i in range(1, 35):
        print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/23/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)
            data["prodi"].append("Teknik Elektro")

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("Elektro.csv", index=False)

    return df

In [ ]:
Elektro()

📄 Memproses halaman ke-1
📄 Memproses halaman ke-2
📄 Memproses halaman ke-3
📄 Memproses halaman ke-4
📄 Memproses halaman ke-5
📄 Memproses halaman ke-6
📄 Memproses halaman ke-7
📄 Memproses halaman ke-8
📄 Memproses halaman ke-9
📄 Memproses halaman ke-10
📄 Memproses halaman ke-11
📄 Memproses halaman ke-12
📄 Memproses halaman ke-13
📄 Memproses halaman ke-14
📄 Memproses halaman ke-15
📄 Memproses halaman ke-16
📄 Memproses halaman ke-17
📄 Memproses halaman ke-18
📄 Memproses halaman ke-19
📄 Memproses halaman ke-20
📄 Memproses halaman ke-21
📄 Memproses halaman ke-22
📄 Memproses halaman ke-23
📄 Memproses halaman ke-24
📄 Memproses halaman ke-25
📄 Memproses halaman ke-26
📄 Memproses halaman ke-27
📄 Memproses halaman ke-28
📄 Memproses halaman ke-29
📄 Memproses halaman ke-30
📄 Memproses halaman ke-31
📄 Memproses halaman ke-32
📄 Memproses halaman ke-33
📄 Memproses halaman ke-34

,penulis,judul,pembimbing_pertama,pembimbing_kedua,abstrak_indo,abstrak_inggris,prodi
0,Achmad Faidi,RANCANG BANGUN PENGATUR TEGANGAN OTOMATIS PADA...,"Koko Joni. S.T., M.Eng.","Achmad Fiqhi Ibadillah, S.T., M.Sc.",Tegangan yang tidak stabil dapat merusak peran...,Unstable voltages can damage electronic device...,Teknik Elektro
1,Dandi Fathur Rohim,SMART GARBAGE BERBASIS INTERNET OF THINGS,"Haryanto. S.T., M.T","Koko Joni. S.T., M.Eng",Sampah di Indonesia merupakan suatu masalah ya...,Trash is one of serious prroblems in Indonesi....,Teknik Elektro
2,Reynanda Bagus Widyo Astomo,Perancangan dan Pembuatan Stop Kontak Berbasis...,,,Pengunaan perangkat elektris dalam kehidupan s...,The use of electrical devices in everyday life...,Teknik Elektro
3,Moh.Nazilus Sa’din Romdloni,PROTOTYPE SISTEM MONITORING DAN PENGENDALIAN P...,"Haryanto,ST,.MT","Riza Alfita,ST,.MT",Indonesia merupakan negara dengan curah hujan ...,Indonesia known as the country with heavy rain...,Teknik Elektro
4,Fajar Dwima Wijaya,Rancang Bangun Sistem Keamanan Parkir Berbasis...,"Diana Rahmawati, S.T., M.T","Kunto Aji Wibisono, S.T., M.T",Sistem pengelolaan tempat parkir pada saat ini...,Parking management system at this time is stil...,Teknik Elektro
...,...,...,...,...,...,...,...
162,Prayogo Teguh Wibowo,Implementasi Convolutional Neural Network Untu...,"Koko Joni, S.T., M.Eng","Achmad Fiqi Ibadillah, S.T., M.Sc",Informasi teks merupakan salah satu komponen p...,,Teknik Elektro
163,KHOLIFATUL SADHIAH,OPTIMALISASI KINERJA PSTN KE VOIP DENGAN MIGRA...,"Ahmad Ubaidillah Ms.,S.T.,MT.","Haryanto, S.T., M.T.",Public Switched Telephone Network (PSTN) adala...,Public Switched Telephone Network (PSTN) is a ...,Teknik Elektro
164,Tantra Juang Ilhami,MONITORING BAHAN BAKAR GENERATOR DENGAN MENGGU...,"Miftachul Ulum ST,.MT.","Riza Alfita, S.T., M.T.",Pemakaian energi listrik semakin lama semakin ...,The use of electricity is increasing as all jo...,Teknik Elektro
165,ACHMAD NUR RIVAI,RANCANGAN SISTEM MOBILE ROBOT SOUND LOCALIZATI...,"DIANA RAHMAWATI,ST.,M.T.","ACHMAD FIQHI IBADILLAH,S.T.,M.Sc",Sistem kontrol robot beroda pada umumnya berbe...,Wheeled robot control systems generally take t...,Teknik Elektro
166,Noer Indra Afriansya,APLIKASI PENGENALAN INFORMASI OBJEK BERSEJARAH...,"Miftachul Ulum, S.T., M.T.","Riza Alfita, S.T., M.T.",Museum Keraton Sumenep merupakan salah satu de...,Sumenep Palace Museum is a destination that is...,Teknik Elektro

Sistem Informasi

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def SI():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": [],
        "prodi" : []
    }

    for i in range(1, 3):
        print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/31/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)
            data["prodi"].append("Sistem Informasi")

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("SI.csv", index=False)

    return df

In [ ]:
SI()

📄 Memproses halaman ke-1
📄 Memproses halaman ke-2

Empty DataFrame
Columns: [penulis, judul, pembimbing_pertama, pembimbing_kedua, abstrak_indo, abstrak_inggris, prodi]
Index: []

Teknik Mesin

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def Mesin():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": [],
        "prodi": []
    }

    for i in range(1, 2):
        print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/31/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)
            data["prodi"].append("Teknik Mesin")

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("Mesin.csv", index=False)

    return df

In [ ]:
Mesin

Teknik Mekatronika

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def Mekatro():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": [],
        "prodi":[]
    }

    for i in range(1, 4):
        print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/33/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)
            data["prodi"].append("Teknik Mekatro")

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("Mekatro.csv", index=False)

    return df

In [ ]:
Mekatro()

📄 Memproses halaman ke-1
📄 Memproses halaman ke-2
📄 Memproses halaman ke-3

,penulis,judul,pembimbing_pertama,pembimbing_kedua,abstrak_indo,abstrak_inggris,prodi
0,Mochamad Izar Bahroni,Kestabilan Autonomous Quadcopter Dengan Kontro...,"Sri Wahyuni, S.Kom., M.T","Faikul Umam, S.Kom., M.T",Unmanned Aerial Vehicle (UAV) memiliki banyak ...,"Unmanned Aerial Vehicle (UAV) has many uses, i...",Teknik Mekatro
1,Moch Zaini,perancangan dan pembuatan sistem rem elektrik ...,"Hairil Budiarto., ST.MT","Faikul Umam., S.Kom.,MT",Kendaraan merupakan suatu alat yang banyak dig...,Vehicle is a tool that is widely used by human...,Teknik Mekatro
2,Mohammad Syafruddin,Pengatur Kerapatan Kertas Pada Alat Penggulung...,"Faikul Umam S.Kom., M.T","Ahmad Sahru Romadhon S.Kom., M.T",PT PAKERIN adalah salah satu pabrik kertas ter...,PT PAKERIN is one of the largest paper mills i...,Teknik Mekatro
3,"Khanif Khoirul Umam, A.Md.",IMPLEMENTASI ALGORITMA MAZE MAPPING PENCARIAN ...,"Sri Wahyuni, S.Kom., M.T.","Hairil Budiarto, S.T.,M.T.",Robot shortest path merupakan jenis robot yang...,Shortest path robot is a type of robot that is...,Teknik Mekatro
4,Achmad Ayubal Ansori,Alat Pengering Rumput Laut Menggunakan Metode ...,"Ahmad Sahru R.,S.Kom.,M.T","Hairil Budiarto S.T.,M.T",Rumput laut merupakan tumbuhan laut yang banya...,Seaweed is a marine plant widely cultivated by...,Teknik Mekatro
5,Raudatul Jannah,ROBOT PENDETEKSI LOKASI KEBOCORAN PADA PIPA LI...,"Vivi Tri .W, S.Kom.,MT.","Hairil Budiarto,ST.,MT.",LPG adalah singkatan dari Liquefied Petroleum ...,LPG stands for Liquefied Petroleum Gas which m...,Teknik Mekatro
6,Ach. Dafid,SISTEM KENDALI KADAR Ph DAN TEMPERATUR TAMBAK ...,"Vivi Tri Widyaningrum, S.Kom.,M.T.","Hairil Budiarto,S.T.,M.T.",Komoditas hewan air yang mampu mengahasilkan d...,Animal water commodities capable of producing ...,Teknik Mekatro
7,MOH HOLIL,PERANCANGAN PROTOTIPE ALAT PENUKAR \nPANAS MEN...,"AHMAD SAHRU ROMADHON.,S.Kom.MT","HAIRIL BUDIARTO.,ST.MT",Perancangan Prototype alat ini dilakukan karen...,Prototype design tool is done because the medi...,Teknik Mekatro
8,Ach Imam Sudianto,PEMANFAATAN ANTI-ROLL TERHADAP KESEIMBANGAN KAPAL,"Hairil Budiarto S.T., M.T","Vivi Tri Widyanningrum S.Kom., M.T.",Kapal adalah alat transportasi pengangkut penu...,The ship is a means of transporting passengers...,Teknik Mekatro
9,MOH TAUFIK HIDAYAT,ALAT PENGGULUNG UNTUK MENGATUR KERAPATAN KERTA...,"FAIKUL UMAM., S.KOM., M.T","SRI WAHYUNI., S.KOM., M.T",ABSTRAK\n\nKertas merupakan kebutuhan yang dib...,ABSTRACT\n\nPaper is a necessity needed by hum...,Teknik Mekatro
10,Alvian Ainun Fajrih,Optimasi Penguapan Air Laut Tua Pada Rumah Kaca,"Hairil Budiarto, S.T., M.T.","Faikul Umam, S.Kom., M.T.",Pembuatan garam di Madura umumnya dilakukan de...,Making salt in Madura is generally done by hea...,Teknik Mekatro
11,ADINDA DEBTIANA DWIKA HILDA,KESTABILAN KECEPATAN MOBILE ROBOT PADA LINTASA...,"Faikul Umam, S.Kom., M.T.","Sri Wahyuni, S.Kom., M.T.",Mobile robot merupakan salah satu kategori rob...,Mobile robot is one of the robot categories th...,Teknik Mekatro
12,Nafizatul Jamilah,Rancang Bangun Sistem Otomasi Robot Pengecatan...,"Hairil Budiarto, S.T., M.T","Sri Wahyuni, S.Kom., M.T",ABSTRAK\n\nMarka jalan raya adalah sebuah tand...,ABSTRACT\n\nA highway mark is a sign that can ...,Teknik Mekatro
13,Agus Salim,Sistem Kestabilan Gerak Robot Omnidirection Me...,"Vivi Tri W, S.Kom., M.T","Ahmad Sahru R, S.Kom., M.T",Di era globalisasi ini sangatlah mungkin tekno...,"In this globalization era, it is very possible...",Teknik Mekatro