# F. Webuage & Nasa

# DATASET WEBUAGE

1. Filter Data Berdasarkan Ekstensi .html

In [8]:
import pandas as pd
from IPython.display import display  # <-- penting untuk tampilan tabel rapi

# Nama file input
file_name = "webuage.csv"

# 1. Muat dataset
print(f"Memuat data dari {file_name}...")
df = pd.read_csv(file_name, sep=';')

# 2. Info dataset
print("\nInfo data asli:")
df.info()

# 3. Tampilkan beberapa baris pertama
print("\nData asli (head):")
display(df.head())   # <-- tampil rapi dalam kotak tabel

# 4. Tentukan kolom target
target_column = "Request URI"

# 5. Cek apakah kolom target ada
if target_column not in df.columns:
    print(f"Error: Kolom '{target_column}' tidak ditemukan di CSV.")
else:
    # 6. Filter data yang diakhiri .html
    print(f"\nMemfilter data untuk baris di mana '{target_column}' diakhiri dengan '.html'...")
    filtered_df = df[df[target_column].str.endswith('.html', na=False)].copy()

    # 7. Simpan hasil filter
    output_filename = "html_requests_only.csv"
    filtered_df.to_csv(output_filename, index=False)

    # 8. Tampilkan hasil filter dalam kotak tabel
    print(f"\nBerhasil menyimpan hasil filter ke '{output_filename}'.")
    print("Pratinjau data hasil filter:")
    display(filtered_df.head())   # <-- tampil rapi dalam kotak tabel

Memuat data dari webuage.csv...

Info data asli:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132258 entries, 0 to 132257
Data columns (total 10 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Remote host                       132258 non-null  object
 1   Remote logname                    132258 non-null  object
 2   Remote user                       132258 non-null  object
 3   Request time                      132258 non-null  object
 4   Request method                    132258 non-null  object
 5   Request URI                       132258 non-null  object
 6   Request Protocol                  132258 non-null  object
 7   Status                            132258 non-null  int64
 8   Size of response (incl. headers)  132258 non-null  int64
 9   Unnamed: 9                        72336 non-null   object
dtypes: int64(2), object(8)
memory usage: 10.1+ MB

Data asli (head):

/tmp/ipython-input-3024135867.py:9: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_name, sep=';')

,Remote host,Remote logname,Remote user,Request time,Request method,Request URI,Request Protocol,Status,Size of response (incl. headers),Unnamed: 9
0,65.55.147.227,-,-,2009-10-15T02:00:24Z,GET,/index.html,HTTP/1.1,200,21878,NaN
1,65.55.86.34,-,-,2009-10-15T02:00:58Z,GET,/index.html,HTTP/1.1,200,1416,NaN
2,148.188.55.88,-,-,2009-10-15T02:01:41Z,GET,/faq.html,HTTP/1.1,200,10946,NaN
3,72.30.57.238,-,-,2009-10-15T02:01:59Z,GET,/contribute.txt,HTTP/1.0,200,39943,NaN
4,66.249.139.233,-,-,2009-10-15T02:02:09Z,GET,/faq.html,HTTP/1.1,200,17247,NaN

Memfilter data untuk baris di mana 'Request URI' diakhiri dengan '.html'...

Berhasil menyimpan hasil filter ke 'html_requests_only.csv'.
Pratinjau data hasil filter:

,Remote host,Remote logname,Remote user,Request time,Request method,Request URI,Request Protocol,Status,Size of response (incl. headers),Unnamed: 9
0,65.55.147.227,-,-,2009-10-15T02:00:24Z,GET,/index.html,HTTP/1.1,200,21878,NaN
1,65.55.86.34,-,-,2009-10-15T02:00:58Z,GET,/index.html,HTTP/1.1,200,1416,NaN
2,148.188.55.88,-,-,2009-10-15T02:01:41Z,GET,/faq.html,HTTP/1.1,200,10946,NaN
4,66.249.139.233,-,-,2009-10-15T02:02:09Z,GET,/faq.html,HTTP/1.1,200,17247,NaN
5,72.30.50.248,-,-,2009-10-15T02:02:13Z,GET,/index.html,HTTP/1.0,200,7883,NaN

2. Filter Data Berdasarkan Status nilai 200

In [9]:
import pandas as pd
from IPython.display import display

# Nama file input (file asli)
file_name = "html_requests_only.csv"

# 1. Muat dataset
print(f"Memuat data dari {file_name}...")
df = pd.read_csv(file_name)

# 2. Tentukan kolom target
target_column = "Status"

# 3. Periksa apakah kolom target ada
if target_column not in df.columns:
    print(f"Error: Kolom '{target_column}' tidak ditemukan di CSV.")
else:
    # 4. Periksa apakah kolomnya numerik
    if pd.api.types.is_numeric_dtype(df[target_column]):

        # 5. Filter baris di mana 'Status' = 200
        print(f"\nMemfilter data untuk baris di mana '{target_column}' adalah 200...")
        filtered_df = df[df[target_column] == 200].copy()

        # 6. Simpan data hasil filter
        output_filename = "status_200_only.csv"
        filtered_df.to_csv(output_filename, index=False)

        # 7. Tampilkan hasil dalam kotak tabel
        print(f"\nBerhasil memfilter data dan menyimpannya ke '{output_filename}'.")
        print("Pratinjau data yang telah difilter:")
        display(filtered_df.head())

    else:
        print(f"Error: Kolom '{target_column}' bukan numerik. Tidak dapat memfilter berdasarkan nilai 200.")

Memuat data dari html_requests_only.csv...

/tmp/ipython-input-2550492120.py:9: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_name)

Memfilter data untuk baris di mana 'Status' adalah 200...

Berhasil memfilter data dan menyimpannya ke 'status_200_only.csv'.
Pratinjau data yang telah difilter:

,Remote host,Remote logname,Remote user,Request time,Request method,Request URI,Request Protocol,Status,Size of response (incl. headers),Unnamed: 9
0,65.55.147.227,-,-,2009-10-15T02:00:24Z,GET,/index.html,HTTP/1.1,200,21878,NaN
1,65.55.86.34,-,-,2009-10-15T02:00:58Z,GET,/index.html,HTTP/1.1,200,1416,NaN
2,148.188.55.88,-,-,2009-10-15T02:01:41Z,GET,/faq.html,HTTP/1.1,200,10946,NaN
3,66.249.139.233,-,-,2009-10-15T02:02:09Z,GET,/faq.html,HTTP/1.1,200,17247,NaN
4,72.30.50.248,-,-,2009-10-15T02:02:13Z,GET,/index.html,HTTP/1.0,200,7883,NaN

3. Mengambil Data Berdasarkan Request Method = GET

In [10]:
import pandas as pd
from IPython.display import display

# Nama file input (file asli)
file_name = "status_200_only.csv"
filter_value = "GET"
target_column = "Request method"

# 1. Muat dataset
print(f"Memuat data dari {file_name}...")
df = pd.read_csv(file_name)

# 2. Periksa apakah kolom target ada
if target_column not in df.columns:
    print(f"Error: Kolom '{target_column}' tidak ditemukan di CSV.")
else:
    # 3. Filter baris di mana 'Request method' sama dengan 'GET'
    print(f"\nMemfilter data untuk baris di mana '{target_column}' adalah '{filter_value}'...")

    filtered_df = df[df[target_column] == filter_value].copy()

    # 4. Simpan data yang telah difilter ke file CSV baru
    output_filename = "method_get_only.csv"
    filtered_df.to_csv(output_filename, index=False)

    # 5. Tampilkan hasil dalam tabel rapi
    print(f"\nBerhasil memfilter data dan menyimpannya ke '{output_filename}'.")
    print("Pratinjau data yang telah difilter:")
    display(filtered_df.head())

Memuat data dari status_200_only.csv...

Memfilter data untuk baris di mana 'Request method' adalah 'GET'...

/tmp/ipython-input-2999871127.py:11: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_name)

Berhasil memfilter data dan menyimpannya ke 'method_get_only.csv'.
Pratinjau data yang telah difilter:

,Remote host,Remote logname,Remote user,Request time,Request method,Request URI,Request Protocol,Status,Size of response (incl. headers),Unnamed: 9
0,65.55.147.227,-,-,2009-10-15T02:00:24Z,GET,/index.html,HTTP/1.1,200,21878,NaN
1,65.55.86.34,-,-,2009-10-15T02:00:58Z,GET,/index.html,HTTP/1.1,200,1416,NaN
2,148.188.55.88,-,-,2009-10-15T02:01:41Z,GET,/faq.html,HTTP/1.1,200,10946,NaN
3,66.249.139.233,-,-,2009-10-15T02:02:09Z,GET,/faq.html,HTTP/1.1,200,17247,NaN
4,72.30.50.248,-,-,2009-10-15T02:02:13Z,GET,/index.html,HTTP/1.0,200,7883,NaN

4. Membersihkan Format Waktu di Kolom Request Time menjadi tanggal dan waktunya

In [11]:
import pandas as pd
from IPython.display import display

# Nama file input (file asli)
file_name = "method_get_only.csv"
target_column = "Request time"

# 1. Muat dataset
print(f"Memuat data dari {file_name}...")
df = pd.read_csv(file_name)

# 2. Periksa apakah kolom target ada
if target_column not in df.columns:
    print(f"Error: Kolom '{target_column}' tidak ditemukan di CSV.")
else:
    # 3. Tampilkan contoh format asli (opsional)
    print(f"Format asli (baris pertama): {df[target_column].iloc[0]}")

    # 4. Bersihkan format datetime
    print(f"Mengubah format kolom '{target_column}'...")
    df[target_column] = df[target_column].str.replace('T', ' ', regex=False)
    df[target_column] = df[target_column].str.replace('Z', '', regex=False)

    # 5. Simpan ke CSV baru
    output_filename = "request_time_cleaned.csv"
    df.to_csv(output_filename, index=False)

    # 6. Tampilkan hasil dalam tabel rapi
    print(f"\nBerhasil mengubah format data dan menyimpannya ke '{output_filename}'.")
    print("Pratinjau data yang telah diubah:")
    display(df.head())

Memuat data dari method_get_only.csv...

/tmp/ipython-input-1162894326.py:10: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_name)

Format asli (baris pertama): 2009-10-15T02:00:24Z
Mengubah format kolom 'Request time'...

Berhasil mengubah format data dan menyimpannya ke 'request_time_cleaned.csv'.
Pratinjau data yang telah diubah:

,Remote host,Remote logname,Remote user,Request time,Request method,Request URI,Request Protocol,Status,Size of response (incl. headers),Unnamed: 9
0,65.55.147.227,-,-,2009-10-15 02:00:24,GET,/index.html,HTTP/1.1,200,21878,NaN
1,65.55.86.34,-,-,2009-10-15 02:00:58,GET,/index.html,HTTP/1.1,200,1416,NaN
2,148.188.55.88,-,-,2009-10-15 02:01:41,GET,/faq.html,HTTP/1.1,200,10946,NaN
3,66.249.139.233,-,-,2009-10-15 02:02:09,GET,/faq.html,HTTP/1.1,200,17247,NaN
4,72.30.50.248,-,-,2009-10-15 02:02:13,GET,/index.html,HTTP/1.0,200,7883,NaN

# TUGAS

## Dataset NASA

1. Membaca Dataset dan Membersihkan Struktur Data

In [13]:
import pandas as pd
from IPython.display import display

# ============================================================
# 1. MEMUAT DATASET NASA LOG (data.csv) DENGAN PEMISAH ';'
#    - Membaca file log
#    - Menetapkan kolom pertama sebagai indeks
#    - Menampilkan info dasar dataset
# ============================================================

file_name = "data.csv"

print(f"Memuat data dari {file_name}...")
df = pd.read_csv(file_name, sep=';', index_col=0)

print("\nInfo data asli:")
display(df.info())

print("\nData asli (head):")
display(df.head())


# ============================================================
# 2. MEMFILTER REQUEST YANG MENGAKSES FILE .html
#    - Mengecek kolom 'url'
#    - Mengambil baris yang URL-nya berakhiran '.html'
#    - Menyimpan hasil ke html_requests_only_NASA.csv
# ============================================================

target_column = "url"

if target_column not in df.columns:
    print(f"Error: Kolom '{target_column}' tidak ditemukan di CSV.")
else:
    print(f"\nMemfilter data untuk baris di mana '{target_column}' diakhiri dengan '.html'...")
    filtered_df = df[df[target_column].str.endswith('.html', na=False)].copy()

    output_filename = "html_requests_only_NASA.csv"
    filtered_df.to_csv(output_filename, sep=';')

    print(f"\nBerhasil memfilter data dan menyimpannya ke {output_filename}.")
    print("Pratinjau data yang telah difilter:")
    display(filtered_df.head())

Memuat data dari data.csv...

/tmp/ipython-input-1897880410.py:14: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_name, sep=';', index_col=0)

Info data asli:
<class 'pandas.core.frame.DataFrame'>
Index: 1048575 entries, 0 to 1048574
Data columns (total 6 columns):
 #   Column    Non-Null Count    Dtype
---  ------    --------------    -----
 0   host      1048575 non-null  object
 1   time      1048575 non-null  int64
 2   method    1048575 non-null  object
 3   url       1048575 non-null  object
 4   response  1048575 non-null  int64
 5   bytes     1048575 non-null  int64
dtypes: int64(3), object(3)
memory usage: 56.0+ MB

None

Data asli (head):

,host,time,method,url,response,bytes
0,***.novo.dk,805465029,GET,/ksc.html,200,7067
1,***.novo.dk,805465031,GET,/images/ksclogo-medium.gif,200,5866
2,***.novo.dk,805465051,GET,/images/MOSAIC-logosmall.gif,200,363
3,***.novo.dk,805465053,GET,/images/USA-logosmall.gif,200,234
4,***.novo.dk,805465054,GET,/images/NASA-logosmall.gif,200,786

Memfilter data untuk baris di mana 'url' diakhiri dengan '.html'...

Berhasil memfilter data dan menyimpannya ke html_requests_only_NASA.csv.
Pratinjau data yang telah difilter:

,host,time,method,url,response,bytes
0,***.novo.dk,805465029,GET,/ksc.html,200,7067
6,***.novo.dk,805465068,GET,/shuttle/missions/missions.html,200,8678
12,***.novo.dk,805465381,GET,/shuttle/resources/orbiters/columbia.html,200,6922
13,***.novo.dk,807951768,GET,/shuttle/missions/sts-69/mission-sts-69.html,200,11264
23,***.novo.dk,807951938,GET,/shuttle/countdown/liftoff.html,200,4665

2. Memfilter Request yang Mengakses Halaman dengan Ekstensi .html

In [3]:
import pandas as pd
from IPython.display import display

# Nama file input
file_name = "data.csv"

# 1. Muat dataset
print(f"Memuat data dari {file_name}...")
df = pd.read_csv(file_name, sep=';', index_col=0)   # sep=';' + index_col=0

# 2. Info data (opsional)
print("\nInfo data asli:")
df.info()

# 3. Tampilkan beberapa baris pertama (dalam kotak)
print("\nData asli (head):")
display(df.head())

# 4. Tentukan kolom target
target_column = "url"

# 5. Periksa apakah kolom target ada
if target_column not in df.columns:
    print(f"Error: Kolom '{target_column}' tidak ditemukan di CSV.")
else:
    # 6. Filter baris berdasarkan ekstensi .html
    print(f"\nMemfilter data untuk baris di mana '{target_column}' diakhiri dengan '.html'...")
    filtered_df = df[df[target_column].str.endswith('.html', na=False)].copy()

    # 7. Simpan data hasil filter
    output_filename = "html_requests_only_NASA.csv"
    filtered_df.to_csv(output_filename, sep=';')

    # 8. Tampilkan hasil dalam kotak
    print(f"\nBerhasil memfilter data dan menyimpannya ke {output_filename}.")
    print("Pratinjau data yang telah difilter:")
    display(filtered_df.head())

Memuat data dari data.csv...

/tmp/ipython-input-3259045496.py:9: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_name, sep=';', index_col=0)   # sep=';' + index_col=0

Info data asli:
<class 'pandas.core.frame.DataFrame'>
Index: 1048575 entries, 0 to 1048574
Data columns (total 6 columns):
 #   Column    Non-Null Count    Dtype
---  ------    --------------    -----
 0   host      1048575 non-null  object
 1   time      1048575 non-null  int64
 2   method    1048575 non-null  object
 3   url       1048575 non-null  object
 4   response  1048575 non-null  int64
 5   bytes     1048575 non-null  int64
dtypes: int64(3), object(3)
memory usage: 56.0+ MB

Data asli (head):

,host,time,method,url,response,bytes
0,***.novo.dk,805465029,GET,/ksc.html,200,7067
1,***.novo.dk,805465031,GET,/images/ksclogo-medium.gif,200,5866
2,***.novo.dk,805465051,GET,/images/MOSAIC-logosmall.gif,200,363
3,***.novo.dk,805465053,GET,/images/USA-logosmall.gif,200,234
4,***.novo.dk,805465054,GET,/images/NASA-logosmall.gif,200,786

Memfilter data untuk baris di mana 'url' diakhiri dengan '.html'...

Berhasil memfilter data dan menyimpannya ke html_requests_only_NASA.csv.
Pratinjau data yang telah difilter:

,host,time,method,url,response,bytes
0,***.novo.dk,805465029,GET,/ksc.html,200,7067
6,***.novo.dk,805465068,GET,/shuttle/missions/missions.html,200,8678
12,***.novo.dk,805465381,GET,/shuttle/resources/orbiters/columbia.html,200,6922
13,***.novo.dk,807951768,GET,/shuttle/missions/sts-69/mission-sts-69.html,200,11264
23,***.novo.dk,807951938,GET,/shuttle/countdown/liftoff.html,200,4665

3. Memfilter Log dengan Status Response 200

In [4]:
import pandas as pd
from IPython.display import display

# Nama file input (file dari langkah sebelumnya)
file_name = "html_requests_only_NASA.csv"

# 1. Muat dataset
print(f"Memuat data dari {file_name}...")
df = pd.read_csv(file_name, sep=';')  # sep=';' untuk file NASA

# 2. Tentukan kolom target
target_column = "response"

# 3. Periksa apakah kolom target ada
if target_column not in df.columns:
    print(f"Error: Kolom '{target_column}' tidak ditemukan di CSV.")

else:
    # 4. Periksa apakah kolomnya numerik
    if pd.api.types.is_numeric_dtype(df[target_column]):

        # 5. Filter baris dengan response == 200
        print(f"\nMemfilter data untuk baris di mana '{target_column}' adalah 200...")
        filtered_df = df[df[target_column] == 200].copy()

        # 6. Simpan hasil filter
        output_filename = "status_200_only_NASA.csv"
        filtered_df.to_csv(output_filename, index=False, sep=';')

        # 7. Tampilkan hasil dalam kotak
        print(f"\nBerhasil memfilter data dan menyimpannya ke {output_filename}.")
        print("Pratinjau data yang telah difilter:")
        display(filtered_df.head())

    else:
        print(f"Error: Kolom '{target_column}' bukan numerik. Periksa pemisah file CSV.")

Memuat data dari html_requests_only_NASA.csv...

/tmp/ipython-input-2217650327.py:9: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_name, sep=';')  # sep=';' untuk file NASA

Memfilter data untuk baris di mana 'response' adalah 200...

Berhasil memfilter data dan menyimpannya ke status_200_only_NASA.csv.
Pratinjau data yang telah difilter:

,Unnamed: 0,host,time,method,url,response,bytes
0,0,***.novo.dk,805465029,GET,/ksc.html,200,7067
1,6,***.novo.dk,805465068,GET,/shuttle/missions/missions.html,200,8678
2,12,***.novo.dk,805465381,GET,/shuttle/resources/orbiters/columbia.html,200,6922
3,13,***.novo.dk,807951768,GET,/shuttle/missions/sts-69/mission-sts-69.html,200,11264
4,23,***.novo.dk,807951938,GET,/shuttle/countdown/liftoff.html,200,4665

4. Memfilter Request yang Menggunakan Metode GET

In [8]:
import pandas as pd
from IPython.display import display  # Tambahan agar hasil tampil dalam kotak

# Nama file input (file dari langkah sebelumnya)
file_name = "status_200_only_NASA.csv"
filter_value = "GET"
# DIUBAH: Nama kolom yang benar adalah 'method', bukan 'Request method'
target_column = "method"

# 1. Muat dataset
print(f"Memuat data dari {file_name}...")
# DIUBAH: Tambahkan sep=';' untuk membaca file dengan benar
df = pd.read_csv(file_name, sep=';')

# 2. Periksa apakah kolom target ada
if target_column not in df.columns:
    print(f"Error: Kolom '{target_column}' tidak ditemukan di CSV.")
else:
    # 3. Filter baris di mana 'method' sama dengan 'GET'
    print(f"\nMemfilter data untuk baris di mana '{target_column}' adalah '{filter_value}'...")

    # Ini adalah baris filter utama (Logika Anda sudah benar)
    filtered_df = df[df[target_column] == filter_value].copy()

    # 4. Simpan data yang telah difilter ke file CSV baru
    output_filename = "method_get_only_NASA.csv"
    # DIUBAH: Tambahkan sep=';' agar konsisten saat menyimpan
    filtered_df.to_csv(output_filename, index=False, sep=';')

    # 5. Cetak pesan sukses dan pratinjau data (opsional)
    print(f"\nBerhasil memfilter data dan menyimpannya ke {output_filename}.")
    print("Pratinjau data yang telah difilter:")
    display(filtered_df.head())  # ← Tampil dalam kotak output

Memuat data dari status_200_only_NASA.csv...

/tmp/ipython-input-1195650344.py:13: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_name, sep=';')

Memfilter data untuk baris di mana 'method' adalah 'GET'...

Berhasil memfilter data dan menyimpannya ke method_get_only_NASA.csv.
Pratinjau data yang telah difilter:

,Unnamed: 0,host,time,method,url,response,bytes
0,0,***.novo.dk,805465029,GET,/ksc.html,200,7067
1,6,***.novo.dk,805465068,GET,/shuttle/missions/missions.html,200,8678
2,12,***.novo.dk,805465381,GET,/shuttle/resources/orbiters/columbia.html,200,6922
3,13,***.novo.dk,807951768,GET,/shuttle/missions/sts-69/mission-sts-69.html,200,11264
4,23,***.novo.dk,807951938,GET,/shuttle/countdown/liftoff.html,200,4665

5. Melakukan perubahan di Request Time menjadi tanggal dan waktunya

In [9]:
import pandas as pd
from IPython.display import display  # Tambahan agar output tampil dalam kotak

# DIUBAH: Nama file input yang benar
file_name = "method_get_only_NASA.csv"
# DIUBAH: Nama kolom target yang benar
target_column = "time"

# 1. Muat dataset
print(f"Memuat data dari {file_name}...")
# DIUBAH: Tambahkan sep=';' untuk membaca file dengan benar
df = pd.read_csv(file_name, sep=';')

# 2. Periksa apakah kolom target ada
if target_column not in df.columns:
    print(f"Error: Kolom '{target_column}' tidak ditemukan di CSV.")
else:
    # 3. Tampilkan contoh format asli (ini adalah Angka/Timestamp)
    print(f"Format asli (baris pertama): {df[target_column].iloc[0]}")

    # 4. Lakukan transformasi:
    #    Kita tidak mengganti 'T' atau 'Z' karena data aslinya adalah angka (Unix timestamp).
    #    Kita akan MENGONVERSI timestamp itu ke format datetime yang mudah dibaca.
    print(f"Mengonversi kolom '{target_column}' (Unix timestamp) ke format Datetime...")

    # pd.to_datetime mengonversi angka timestamp (unit='s' berarti 'seconds')
    # Kita buat kolom baru 'datetime_readable' agar data asli tidak hilang
    df['datetime_readable'] = pd.to_datetime(df[target_column], unit='s')

    # 5. Simpan data yang telah diubah ke file CSV baru
    output_filename = "time_converted_NASA.csv"
    # DIUBAH: Tambahkan sep=';' agar konsisten
    df.to_csv(output_filename, index=False, sep=';')

    # 6. Cetak pesan sukses dan pratinjau
    print(f"\nBerhasil mengonversi data waktu dan menyimpannya ke {output_filename}.")
    print("Pratinjau data yang telah diubah (lihat kolom baru 'datetime_readable'):")

    display(df.head())  # ← tampil rapi dalam kotak

Memuat data dari method_get_only_NASA.csv...

/tmp/ipython-input-3405792236.py:12: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_name, sep=';')

Format asli (baris pertama): 805465029
Mengonversi kolom 'time' (Unix timestamp) ke format Datetime...

Berhasil mengonversi data waktu dan menyimpannya ke time_converted_NASA.csv.
Pratinjau data yang telah diubah (lihat kolom baru 'datetime_readable'):

,Unnamed: 0,host,time,method,url,response,bytes,datetime_readable
0,0,***.novo.dk,805465029,GET,/ksc.html,200,7067,1995-07-11 12:17:09
1,6,***.novo.dk,805465068,GET,/shuttle/missions/missions.html,200,8678,1995-07-11 12:17:48
2,12,***.novo.dk,805465381,GET,/shuttle/resources/orbiters/columbia.html,200,6922,1995-07-11 12:23:01
3,13,***.novo.dk,807951768,GET,/shuttle/missions/sts-69/mission-sts-69.html,200,11264,1995-08-09 07:02:48
4,23,***.novo.dk,807951938,GET,/shuttle/countdown/liftoff.html,200,4665,1995-08-09 07:05:38

6. Membuat Kolom pada session berdasarkan Host, Mengurutkan Berdasarkan Waktu, dan Menyimpan Tabel Final

In [10]:
import pandas as pd
from IPython.display import display  # Tambahan untuk tampilan kotak tabel

# 1. Tentukan file input (file yang memiliki 'datetime_readable')
file_name = "time_converted_NASA.csv"

# 2. Tentukan kolom-kolom yang akan kita gunakan
col_ip = "host"                # Kolom untuk mengelompokkan sesi
col_time = "datetime_readable" # Kolom untuk mengurutkan sesi
new_col_name = "SESSION"       # Nama kolom sesi baru

print(f"Memuat data dari {file_name}...")
try:
    # 3. Muat dataset
    df = pd.read_csv(file_name, sep=';', parse_dates=[col_time])
except FileNotFoundError:
    print(f"Error: File {file_name} tidak ditemukan.")
    print("Pastikan Anda sudah menjalankan skrip konversi 'time' sebelumnya.")
    exit()
except ValueError as e:
    print(f"Error saat membaca {file_name}. Cek kolom '{col_time}'.")
    print(f"Detail: {e}")
    exit()


# 4. Periksa apakah kolom yang diperlukan ada
if col_ip in df.columns and col_time in df.columns:

    # 5. BUAT KOLOM SESSION
    print(f"Membuat kolom '{new_col_name}' berdasarkan '{col_ip}' unik...")
    df[new_col_name] = df[col_ip].astype('category').cat.codes + 1

    # 6. Urutkan data berdasarkan SESSION dan WAKTU
    print(f"Mengurutkan data berdasarkan '{new_col_name}' dan '{col_time}'...")
    df_sorted = df.sort_values(by=[new_col_name, col_time], ascending=True)

    # 7. Hapus kolom 'time' asli jika masih ada
    if 'time' in df_sorted.columns:
        print("Menghapus kolom 'time' (timestamp unix) asli...")
        df_sorted = df_sorted.drop(columns=['time'])

    # 8. Simpan DataFrame hasil proses
    output_filename = "session_data_full_NASA.csv"

    print(f"Menyimpan data ke {output_filename} dengan pemisah KOMA (',')...")
    df_sorted.to_csv(output_filename, index=False, sep=',')

    print(f"\nBerhasil! Kolom '{new_col_name}' telah ditambahkan.")
    print(f"File baru disimpan sebagai: {output_filename}")
    print("\nPratinjau data baru:")

    # Pratinjau rapi menggunakan display()
    preview_cols = [new_col_name, col_ip, col_time, 'url']
    display(df_sorted[preview_cols].head())

else:
    print(f"Error: Kolom '{col_ip}' atau '{col_time}' tidak ditemukan di {file_name}.")

Memuat data dari time_converted_NASA.csv...

/tmp/ipython-input-1909776655.py:15: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_name, sep=';', parse_dates=[col_time])

Membuat kolom 'SESSION' berdasarkan 'host' unik...
Mengurutkan data berdasarkan 'SESSION' dan 'datetime_readable'...
Menghapus kolom 'time' (timestamp unix) asli...
Menyimpan data ke session_data_full_NASA.csv dengan pemisah KOMA (',')...

Berhasil! Kolom 'SESSION' telah ditambahkan.
File baru disimpan sebagai: session_data_full_NASA.csv

Pratinjau data baru:

,SESSION,host,datetime_readable,url
0,1,***.novo.dk,1995-07-11 12:17:09,/ksc.html
1,1,***.novo.dk,1995-07-11 12:17:48,/shuttle/missions/missions.html
2,1,***.novo.dk,1995-07-11 12:23:01,/shuttle/resources/orbiters/columbia.html
3,1,***.novo.dk,1995-08-09 07:02:48,/shuttle/missions/sts-69/mission-sts-69.html
4,1,***.novo.dk,1995-08-09 07:05:38,/shuttle/countdown/liftoff.html

In [11]:
import pandas as pd
from IPython.display import display  # Tambahan agar output tampil dalam kotak

# 1. Tentukan file input (file yang memiliki 'datetime_readable')
file_name = "time_converted_NASA.csv"

# 2. Tentukan kolom-kolom yang akan kita gunakan
col_ip = "host"                # Kolom untuk mengelompokkan sesi
col_time = "datetime_readable" # Kolom untuk mengurutkan sesi
new_col_name = "SESSION"       # Nama kolom sesi baru

print(f"Memuat data dari {file_name}...")
try:
    # 3. Muat dataset (pemisah asli adalah ';')
    df = pd.read_csv(file_name, sep=';', parse_dates=[col_time])
except FileNotFoundError:
    print(f"Error: File {file_name} tidak ditemukan.")
    print("Pastikan Anda sudah menjalankan skrip konversi 'time' sebelumnya.")
    exit()
except ValueError as e:
    print(f"Error saat membaca {file_name}. Cek kolom '{col_time}'.")
    print(f"Detail: {e}")
    exit()


# 4. Periksa apakah kolom yang diperlukan ada
if col_ip in df.columns and col_time in df.columns:

    # 5. BUAT KOLOM SESSION (Logika sama seperti sebelumnya)
    print(f"Membuat kolom '{new_col_name}' berdasarkan '{col_ip}' unik...")
    df[new_col_name] = df[col_ip].astype('category').cat.codes + 1

    # 6. Urutkan data berdasarkan SESSION dan WAKTU
    print(f"Mengurutkan data berdasarkan '{new_col_name}' dan '{col_time}'...")
    df_sorted = df.sort_values(by=[new_col_name, col_time], ascending=True)

    # --- DIUBAH DI SINI ---

    # 8. Kolom yang ingin dipertahankan
    columns_to_keep = ['SESSION', 'host', 'datetime_readable', 'url']

    print(f"\nMemfilter data untuk HANYA menyimpan kolom: {columns_to_keep}...")
    df_final_output = df_sorted[columns_to_keep].copy()

    # 9. Simpan DataFrame hasil akhir
    output_filename = "session_host_time_url_NASA.csv"

    print(f"Menyimpan data ke {output_filename} dengan pemisah KOMA (',')...")
    df_final_output.to_csv(output_filename, index=False, sep=',')

    print(f"\nBerhasil! File baru disimpan sebagai: {output_filename}.")
    print("\nPratinjau data baru (4 kolom):")

    # Tampilkan dalam kotak
    display(df_final_output.head())

else:
    print(f"Error: Kolom '{col_ip}' atau '{col_time}' tidak ditemukan di {file_name}.")

Memuat data dari time_converted_NASA.csv...

/tmp/ipython-input-2823329595.py:15: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_name, sep=';', parse_dates=[col_time])

Membuat kolom 'SESSION' berdasarkan 'host' unik...
Mengurutkan data berdasarkan 'SESSION' dan 'datetime_readable'...

Memfilter data untuk HANYA menyimpan kolom: ['SESSION', 'host', 'datetime_readable', 'url']...
Menyimpan data ke session_host_time_url_NASA.csv dengan pemisah KOMA (',')...

Berhasil! File baru disimpan sebagai: session_host_time_url_NASA.csv.

Pratinjau data baru (4 kolom):

,SESSION,host,datetime_readable,url
0,1,***.novo.dk,1995-07-11 12:17:09,/ksc.html
1,1,***.novo.dk,1995-07-11 12:17:48,/shuttle/missions/missions.html
2,1,***.novo.dk,1995-07-11 12:23:01,/shuttle/resources/orbiters/columbia.html
3,1,***.novo.dk,1995-08-09 07:02:48,/shuttle/missions/sts-69/mission-sts-69.html
4,1,***.novo.dk,1995-08-09 07:05:38,/shuttle/countdown/liftoff.html