# F. Webuage&NASA

# DATASET WEBUAGE

##1.Filter Data Berdasarkan Ekstensi .html

In [ ]:
import pandas as pd
from IPython.display import display

# Nama file input
file_name = "webuage.csv"

# 1. Muat dataset
print(f"Memuat data dari {file_name}...")
df = pd.read_csv(file_name, sep=';')

# 2. Info dataset
print("\nInfo data asli:")
df.info()

# 3. Tampilkan beberapa baris pertama
print("\nData asli (head):")
display(df.head())

# 4. Tentukan kolom target
target_column = "Request URI"

# 5. Cek apakah kolom target ada
if target_column not in df.columns:
    print(f"Error: Kolom '{target_column}' tidak ditemukan di CSV.")
else:
    # 6. Filter data yang diakhiri .html
    print(f"\nMemfilter data untuk baris di mana '{target_column}' diakhiri dengan '.html'...")
    filtered_df = df[df[target_column].str.endswith('.html', na=False)].copy()

    # 7. Simpan hasil filter
    output_filename = "html_requests_only.csv"
    filtered_df.to_csv(output_filename, index=False)

    # 8. Tampilkan hasil filter dalam kotak tabel
    print(f"\nBerhasil menyimpan hasil filter ke '{output_filename}'.")
    print("Pratinjau data hasil filter:")
    display(filtered_df.head())

Memuat data dari webuage.csv...

Info data asli:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132258 entries, 0 to 132257
Data columns (total 10 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Remote host                       132258 non-null  object
 1   Remote logname                    132258 non-null  object
 2   Remote user                       132258 non-null  object
 3   Request time                      132258 non-null  object
 4   Request method                    132258 non-null  object
 5   Request URI                       132258 non-null  object
 6   Request Protocol                  132258 non-null  object
 7   Status                            132258 non-null  int64
 8   Size of response (incl. headers)  132258 non-null  int64
 9   Unnamed: 9                        72336 non-null   object
dtypes: int64(2), object(8)
memory usage: 10.1+ MB

Data asli (head):

/tmp/ipython-input-2266985052.py:9: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_name, sep=';')

,Remote host,Remote logname,Remote user,Request time,Request method,Request URI,Request Protocol,Status,Size of response (incl. headers),Unnamed: 9
0,65.55.147.227,-,-,2009-10-15T02:00:24Z,GET,/index.html,HTTP/1.1,200,21878,NaN
1,65.55.86.34,-,-,2009-10-15T02:00:58Z,GET,/index.html,HTTP/1.1,200,1416,NaN
2,148.188.55.88,-,-,2009-10-15T02:01:41Z,GET,/faq.html,HTTP/1.1,200,10946,NaN
3,72.30.57.238,-,-,2009-10-15T02:01:59Z,GET,/contribute.txt,HTTP/1.0,200,39943,NaN
4,66.249.139.233,-,-,2009-10-15T02:02:09Z,GET,/faq.html,HTTP/1.1,200,17247,NaN

Memfilter data untuk baris di mana 'Request URI' diakhiri dengan '.html'...

Berhasil menyimpan hasil filter ke 'html_requests_only.csv'.
Pratinjau data hasil filter:

,Remote host,Remote logname,Remote user,Request time,Request method,Request URI,Request Protocol,Status,Size of response (incl. headers),Unnamed: 9
0,65.55.147.227,-,-,2009-10-15T02:00:24Z,GET,/index.html,HTTP/1.1,200,21878,NaN
1,65.55.86.34,-,-,2009-10-15T02:00:58Z,GET,/index.html,HTTP/1.1,200,1416,NaN
2,148.188.55.88,-,-,2009-10-15T02:01:41Z,GET,/faq.html,HTTP/1.1,200,10946,NaN
4,66.249.139.233,-,-,2009-10-15T02:02:09Z,GET,/faq.html,HTTP/1.1,200,17247,NaN
5,72.30.50.248,-,-,2009-10-15T02:02:13Z,GET,/index.html,HTTP/1.0,200,7883,NaN

##2.Filter Data Berdasarkan Status nilai 200

In [ ]:
import pandas as pd
from IPython.display import display

# Nama file input (file asli)
file_name = "html_requests_only.csv"

# 1. Muat dataset
print(f"Memuat data dari {file_name}...")
df = pd.read_csv(file_name)

# 2. Tentukan kolom target
target_column = "Status"

# 3. Periksa apakah kolom target ada
if target_column not in df.columns:
    print(f"Error: Kolom '{target_column}' tidak ditemukan di CSV.")
else:
    # 4. Periksa apakah kolomnya numerik
    if pd.api.types.is_numeric_dtype(df[target_column]):

        # 5. Filter baris di mana 'Status' = 200
        print(f"\nMemfilter data untuk baris di mana '{target_column}' adalah 200...")
        filtered_df = df[df[target_column] == 200].copy()

        # 6. Simpan data hasil filter
        output_filename = "status_200_only.csv"
        filtered_df.to_csv(output_filename, index=False)

        # 7. Tampilkan hasil dalam kotak tabel
        print(f"\nBerhasil memfilter data dan menyimpannya ke '{output_filename}'.")
        print("Pratinjau data yang telah difilter:")
        display(filtered_df.head())

    else:
        print(f"Error: Kolom '{target_column}' bukan numerik. Tidak dapat memfilter berdasarkan nilai 200.")

Memuat data dari html_requests_only.csv...

/tmp/ipython-input-2550492120.py:9: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_name)

Memfilter data untuk baris di mana 'Status' adalah 200...

Berhasil memfilter data dan menyimpannya ke 'status_200_only.csv'.
Pratinjau data yang telah difilter:

,Remote host,Remote logname,Remote user,Request time,Request method,Request URI,Request Protocol,Status,Size of response (incl. headers),Unnamed: 9
0,65.55.147.227,-,-,2009-10-15T02:00:24Z,GET,/index.html,HTTP/1.1,200,21878,NaN
1,65.55.86.34,-,-,2009-10-15T02:00:58Z,GET,/index.html,HTTP/1.1,200,1416,NaN
2,148.188.55.88,-,-,2009-10-15T02:01:41Z,GET,/faq.html,HTTP/1.1,200,10946,NaN
3,66.249.139.233,-,-,2009-10-15T02:02:09Z,GET,/faq.html,HTTP/1.1,200,17247,NaN
4,72.30.50.248,-,-,2009-10-15T02:02:13Z,GET,/index.html,HTTP/1.0,200,7883,NaN

##3.Mengambil Data Berdasarkan Request Method = GET

In [ ]:
import pandas as pd
from IPython.display import display

# Nama file input (file asli)
file_name = "status_200_only.csv"
filter_value = "GET"
target_column = "Request method"

# 1. Muat dataset
print(f"Memuat data dari {file_name}...")
df = pd.read_csv(file_name)

# 2. Periksa apakah kolom target ada
if target_column not in df.columns:
    print(f"Error: Kolom '{target_column}' tidak ditemukan di CSV.")
else:
    # 3. Filter baris di mana 'Request method' sama dengan 'GET'
    print(f"\nMemfilter data untuk baris di mana '{target_column}' adalah '{filter_value}'...")

    filtered_df = df[df[target_column] == filter_value].copy()

    # 4. Simpan data yang telah difilter ke file CSV baru
    output_filename = "method_get_only.csv"
    filtered_df.to_csv(output_filename, index=False)

    # 5. Tampilkan hasil dalam tabel rapi
    print(f"\nBerhasil memfilter data dan menyimpannya ke '{output_filename}'.")
    print("Pratinjau data yang telah difilter:")
    display(filtered_df.head())

Memuat data dari status_200_only.csv...

/tmp/ipython-input-2999871127.py:11: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_name)

Memfilter data untuk baris di mana 'Request method' adalah 'GET'...

Berhasil memfilter data dan menyimpannya ke 'method_get_only.csv'.
Pratinjau data yang telah difilter:

,Remote host,Remote logname,Remote user,Request time,Request method,Request URI,Request Protocol,Status,Size of response (incl. headers),Unnamed: 9
0,65.55.147.227,-,-,2009-10-15T02:00:24Z,GET,/index.html,HTTP/1.1,200,21878,NaN
1,65.55.86.34,-,-,2009-10-15T02:00:58Z,GET,/index.html,HTTP/1.1,200,1416,NaN
2,148.188.55.88,-,-,2009-10-15T02:01:41Z,GET,/faq.html,HTTP/1.1,200,10946,NaN
3,66.249.139.233,-,-,2009-10-15T02:02:09Z,GET,/faq.html,HTTP/1.1,200,17247,NaN
4,72.30.50.248,-,-,2009-10-15T02:02:13Z,GET,/index.html,HTTP/1.0,200,7883,NaN

##4.Membersihkan Format Waktu di Kolom Request Time menjadi tanggal dan waktunya

In [ ]:
import pandas as pd
from IPython.display import display

# Nama file input (file asli)
file_name = "method_get_only.csv"
target_column = "Request time"

# 1. Muat dataset
print(f"Memuat data dari {file_name}...")
df = pd.read_csv(file_name)

# 2. Periksa apakah kolom target ada
if target_column not in df.columns:
    print(f"Error: Kolom '{target_column}' tidak ditemukan di CSV.")
else:
    # 3. Tampilkan contoh format asli (opsional)
    print(f"Format asli (baris pertama): {df[target_column].iloc[0]}")

    # 4. Bersihkan format datetime
    print(f"Mengubah format kolom '{target_column}'...")
    df[target_column] = df[target_column].str.replace('T', ' ', regex=False)
    df[target_column] = df[target_column].str.replace('Z', '', regex=False)

    # 5. Simpan ke CSV baru
    output_filename = "request_time_cleaned.csv"
    df.to_csv(output_filename, index=False)

    # 6. Tampilkan hasil dalam tabel rapi
    print(f"\nBerhasil mengubah format data dan menyimpannya ke '{output_filename}'.")
    print("Pratinjau data yang telah diubah:")
    display(df.head())

Memuat data dari method_get_only.csv...

/tmp/ipython-input-1162894326.py:10: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_name)

Format asli (baris pertama): 2009-10-15T02:00:24Z
Mengubah format kolom 'Request time'...

Berhasil mengubah format data dan menyimpannya ke 'request_time_cleaned.csv'.
Pratinjau data yang telah diubah:

,Remote host,Remote logname,Remote user,Request time,Request method,Request URI,Request Protocol,Status,Size of response (incl. headers),Unnamed: 9
0,65.55.147.227,-,-,2009-10-15 02:00:24,GET,/index.html,HTTP/1.1,200,21878,NaN
1,65.55.86.34,-,-,2009-10-15 02:00:58,GET,/index.html,HTTP/1.1,200,1416,NaN
2,148.188.55.88,-,-,2009-10-15 02:01:41,GET,/faq.html,HTTP/1.1,200,10946,NaN
3,66.249.139.233,-,-,2009-10-15 02:02:09,GET,/faq.html,HTTP/1.1,200,17247,NaN
4,72.30.50.248,-,-,2009-10-15 02:02:13,GET,/index.html,HTTP/1.0,200,7883,NaN

# TUGAS

## Dataset NASA

##1.Membaca Dataset

In [ ]:
import pandas as pd
from IPython.display import display

# ============================================================
# 1. MEMUAT DATASET NASA LOG (data.csv) DENGAN PEMISAH ';'
#    - Membaca file log
#    - Menetapkan kolom pertama sebagai indeks
#    - Menampilkan info dasar dataset
# ============================================================

file_name = "data.csv"

print(f"Memuat data dari {file_name}...")
df = pd.read_csv(file_name, sep=';', index_col=0)

print("\nInfo data asli:")
display(df.info())

print("\nData asli (head):")
display(df.head())


# ============================================================
# 2. MEMFILTER REQUEST YANG MENGAKSES FILE .html
#    - Mengecek kolom 'url'
#    - Mengambil baris yang URL-nya berakhiran '.html'
#    - Menyimpan hasil ke html_requests_only_data.csv
# ============================================================

target_column = "url"

if target_column not in df.columns:
    print(f"Error: Kolom '{target_column}' tidak ditemukan di CSV.")
else:
    print(f"\nMemfilter data untuk baris di mana '{target_column}' diakhiri dengan '.html'...")
    filtered_df = df[df[target_column].str.endswith('.html', na=False)].copy()

    output_filename = "html_requests_only_NASA.csv"
    filtered_df.to_csv(output_filename, sep=';')

    print(f"\nBerhasil memfilter data dan menyimpannya ke {output_filename}.")
    print("Pratinjau data yang telah difilter:")
    display(filtered_df.head())

Memuat data dari data.csv...

Info data asli:
<class 'pandas.core.frame.DataFrame'>
Index: 309514 entries, 0 to 309513
Data columns (total 6 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   host      309514 non-null  object
 1   time      309514 non-null  int64
 2   method    309514 non-null  object
 3   url       309514 non-null  object
 4   response  309513 non-null  float64
 5   bytes     309513 non-null  float64
dtypes: float64(2), int64(1), object(3)
memory usage: 16.5+ MB

None

Data asli (head):

,host,time,method,url,response,bytes
0,***.novo.dk,805465029,GET,/ksc.html,200.0,7067.0
1,***.novo.dk,805465031,GET,/images/ksclogo-medium.gif,200.0,5866.0
2,***.novo.dk,805465051,GET,/images/MOSAIC-logosmall.gif,200.0,363.0
3,***.novo.dk,805465053,GET,/images/USA-logosmall.gif,200.0,234.0
4,***.novo.dk,805465054,GET,/images/NASA-logosmall.gif,200.0,786.0

Memfilter data untuk baris di mana 'url' diakhiri dengan '.html'...

Berhasil memfilter data dan menyimpannya ke html_requests_only_NASA.csv.
Pratinjau data yang telah difilter:

,host,time,method,url,response,bytes
0,***.novo.dk,805465029,GET,/ksc.html,200.0,7067.0
6,***.novo.dk,805465068,GET,/shuttle/missions/missions.html,200.0,8678.0
12,***.novo.dk,805465381,GET,/shuttle/resources/orbiters/columbia.html,200.0,6922.0
13,***.novo.dk,807951768,GET,/shuttle/missions/sts-69/mission-sts-69.html,200.0,11264.0
23,***.novo.dk,807951938,GET,/shuttle/countdown/liftoff.html,200.0,4665.0

##2.Memfilter Request yang Mengakses Halaman dengan Ekstensi .html

In [ ]:
import pandas as pd
from IPython.display import display

# Nama file input
file_name = "data.csv"

# 1. Muat dataset
print(f"Memuat data dari {file_name}...")
df = pd.read_csv(file_name, sep=';', index_col=0)   # sep=';' + index_col=0

# 2. Info data (opsional)
print("\nInfo data asli:")
df.info()

# 3. Tampilkan beberapa baris pertama (dalam kotak)
print("\nData asli (head):")
display(df.head())

# 4. Tentukan kolom target
target_column = "url"

# 5. Periksa apakah kolom target ada
if target_column not in df.columns:
    print(f"Error: Kolom '{target_column}' tidak ditemukan di CSV.")
else:
    # 6. Filter baris berdasarkan ekstensi .html
    print(f"\nMemfilter data untuk baris di mana '{target_column}' diakhiri dengan '.html'...")
    filtered_df = df[df[target_column].str.endswith('.html', na=False)].copy()

    # 7. Simpan data hasil filter
    output_filename = "html_requests_only_NASA.csv"
    filtered_df.to_csv(output_filename, sep=';')

    # 8. Tampilkan hasil dalam kotak
    print(f"\nBerhasil memfilter data dan menyimpannya ke {output_filename}.")
    print("Pratinjau data yang telah difilter:")
    display(filtered_df.head())

Memuat data dari data.csv...

Info data asli:
<class 'pandas.core.frame.DataFrame'>
Index: 309514 entries, 0 to 309513
Data columns (total 6 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   host      309514 non-null  object
 1   time      309514 non-null  int64
 2   method    309514 non-null  object
 3   url       309514 non-null  object
 4   response  309513 non-null  float64
 5   bytes     309513 non-null  float64
dtypes: float64(2), int64(1), object(3)
memory usage: 16.5+ MB

Data asli (head):

,host,time,method,url,response,bytes
0,***.novo.dk,805465029,GET,/ksc.html,200.0,7067.0
1,***.novo.dk,805465031,GET,/images/ksclogo-medium.gif,200.0,5866.0
2,***.novo.dk,805465051,GET,/images/MOSAIC-logosmall.gif,200.0,363.0
3,***.novo.dk,805465053,GET,/images/USA-logosmall.gif,200.0,234.0
4,***.novo.dk,805465054,GET,/images/NASA-logosmall.gif,200.0,786.0

Memfilter data untuk baris di mana 'url' diakhiri dengan '.html'...

Berhasil memfilter data dan menyimpannya ke html_requests_only_NASA.csv.
Pratinjau data yang telah difilter:

,host,time,method,url,response,bytes
0,***.novo.dk,805465029,GET,/ksc.html,200.0,7067.0
6,***.novo.dk,805465068,GET,/shuttle/missions/missions.html,200.0,8678.0
12,***.novo.dk,805465381,GET,/shuttle/resources/orbiters/columbia.html,200.0,6922.0
13,***.novo.dk,807951768,GET,/shuttle/missions/sts-69/mission-sts-69.html,200.0,11264.0
23,***.novo.dk,807951938,GET,/shuttle/countdown/liftoff.html,200.0,4665.0

##3.Memfilter Log dengan Status Response 200

In [ ]:
import pandas as pd
from IPython.display import display

# Nama file input (file dari langkah sebelumnya)
file_name = "html_requests_only_NASA.csv"

# 1. Muat dataset
print(f"Memuat data dari {file_name}...")
df = pd.read_csv(file_name, sep=';')  # sep=';' untuk file NASA

# 2. Tentukan kolom target
target_column = "response"

# 3. Periksa apakah kolom target ada
if target_column not in df.columns:
    print(f"Error: Kolom '{target_column}' tidak ditemukan di CSV.")

else:
    # 4. Periksa apakah kolomnya numerik
    if pd.api.types.is_numeric_dtype(df[target_column]):

        # 5. Filter baris dengan response == 200
        print(f"\nMemfilter data untuk baris di mana '{target_column}' adalah 200...")
        filtered_df = df[df[target_column] == 200].copy()

        # 6. Simpan hasil filter
        output_filename = "status_200_only_NASA.csv"
        filtered_df.to_csv(output_filename, index=False, sep=';')

        # 7. Tampilkan hasil dalam kotak
        print(f"\nBerhasil memfilter data dan menyimpannya ke {output_filename}.")
        print("Pratinjau data yang telah difilter:")
        display(filtered_df.head())

    else:
        print(f"Error: Kolom '{target_column}' bukan numerik. Periksa pemisah file CSV.")

Memuat data dari html_requests_only_NASA.csv...

Memfilter data untuk baris di mana 'response' adalah 200...

Berhasil memfilter data dan menyimpannya ke status_200_only_NASA.csv.
Pratinjau data yang telah difilter:

,Unnamed: 0,host,time,method,url,response,bytes
0,0,***.novo.dk,805465029,GET,/ksc.html,200.0,7067.0
1,6,***.novo.dk,805465068,GET,/shuttle/missions/missions.html,200.0,8678.0
2,12,***.novo.dk,805465381,GET,/shuttle/resources/orbiters/columbia.html,200.0,6922.0
3,13,***.novo.dk,807951768,GET,/shuttle/missions/sts-69/mission-sts-69.html,200.0,11264.0
4,23,***.novo.dk,807951938,GET,/shuttle/countdown/liftoff.html,200.0,4665.0

##4.Memfilter Request yang Menggunakan Metode GET

In [ ]:
import pandas as pd
from IPython.display import display  # Tambahan agar hasil tampil dalam kotak

# Nama file input (file dari langkah sebelumnya)
file_name = "status_200_only_NASA.csv"
filter_value = "GET"
# DIUBAH: Nama kolom yang benar adalah 'method', bukan 'Request method'
target_column = "method"

# 1. Muat dataset
print(f"Memuat data dari {file_name}...")
# DIUBAH: Tambahkan sep=';' untuk membaca file dengan benar
df = pd.read_csv(file_name, sep=';')

# 2. Periksa apakah kolom target ada
if target_column not in df.columns:
    print(f"Error: Kolom '{target_column}' tidak ditemukan di CSV.")
else:
    # 3. Filter baris di mana 'method' sama dengan 'GET'
    print(f"\nMemfilter data untuk baris di mana '{target_column}' adalah '{filter_value}'...")

    # Ini adalah baris filter utama (Logika Anda sudah benar)
    filtered_df = df[df[target_column] == filter_value].copy()

    # 4. Simpan data yang telah difilter ke file CSV baru
    output_filename = "method_get_only_NASA.csv"
    # DIUBAH: Tambahkan sep=';' agar konsisten saat menyimpan
    filtered_df.to_csv(output_filename, index=False, sep=';')

    # 5. Cetak pesan sukses dan pratinjau data (opsional)
    print(f"\nBerhasil memfilter data dan menyimpannya ke {output_filename}.")
    print("Pratinjau data yang telah difilter:")
    display(filtered_df.head())  # ← Tampil dalam kotak output

Memuat data dari status_200_only_NASA.csv...

Memfilter data untuk baris di mana 'method' adalah 'GET'...

Berhasil memfilter data dan menyimpannya ke method_get_only_NASA.csv.
Pratinjau data yang telah difilter:

,Unnamed: 0,host,time,method,url,response,bytes
0,0,***.novo.dk,805465029,GET,/ksc.html,200.0,7067.0
1,6,***.novo.dk,805465068,GET,/shuttle/missions/missions.html,200.0,8678.0
2,12,***.novo.dk,805465381,GET,/shuttle/resources/orbiters/columbia.html,200.0,6922.0
3,13,***.novo.dk,807951768,GET,/shuttle/missions/sts-69/mission-sts-69.html,200.0,11264.0
4,23,***.novo.dk,807951938,GET,/shuttle/countdown/liftoff.html,200.0,4665.0

##5.Melakukan perubahan di Request Time menjadi tanggal dan waktunya

In [ ]:
import pandas as pd
from IPython.display import display

# DIUBAH: Nama file input yang benar
file_name = "method_get_only_NASA.csv"
# DIUBAH: Nama kolom target yang benar
target_column = "time"

# 1. Muat dataset
print(f"Memuat data dari {file_name}...")
# DIUBAH: Tambahkan sep=';' untuk membaca file dengan benar
df = pd.read_csv(file_name, sep=';')

# 2. Periksa apakah kolom target ada
if target_column not in df.columns:
    print(f"Error: Kolom '{target_column}' tidak ditemukan di CSV.")
else:
    # 3. Tampilkan contoh format asli (ini adalah Angka/Timestamp)
    print(f"Format asli (baris pertama): {df[target_column].iloc[0]}")

    # 4. Lakukan transformasi:
    #    Kita tidak mengganti 'T' atau 'Z' karena data aslinya adalah angka (Unix timestamp).
    #    Kita akan MENGONVERSI timestamp itu ke format datetime yang mudah dibaca.
    print(f"Mengonversi kolom '{target_column}' (Unix timestamp) ke format Datetime...")

    # pd.to_datetime mengonversi angka timestamp (unit='s' berarti 'seconds')
    # Kita buat kolom baru 'datetime_readable' agar data asli tidak hilang
    df['datetime_readable'] = pd.to_datetime(df[target_column], unit='s')

    # 5. Simpan data yang telah diubah ke file CSV baru
    output_filename = "time_converted_NASA.csv"
    # DIUBAH: Tambahkan sep=';' agar konsisten
    df.to_csv(output_filename, index=False, sep=';')

    # 6. Cetak pesan sukses dan pratinjau
    print(f"\nBerhasil mengonversi data waktu dan menyimpannya ke {output_filename}.")
    print("Pratinjau data yang telah diubah (lihat kolom baru 'datetime_readable'):")

    display(df.head())

Memuat data dari method_get_only_NASA.csv...
Format asli (baris pertama): 805465029
Mengonversi kolom 'time' (Unix timestamp) ke format Datetime...

Berhasil mengonversi data waktu dan menyimpannya ke time_converted_NASA.csv.
Pratinjau data yang telah diubah (lihat kolom baru 'datetime_readable'):

,Unnamed: 0,host,time,method,url,response,bytes,datetime_readable
0,0,***.novo.dk,805465029,GET,/ksc.html,200.0,7067.0,1995-07-11 12:17:09
1,6,***.novo.dk,805465068,GET,/shuttle/missions/missions.html,200.0,8678.0,1995-07-11 12:17:48
2,12,***.novo.dk,805465381,GET,/shuttle/resources/orbiters/columbia.html,200.0,6922.0,1995-07-11 12:23:01
3,13,***.novo.dk,807951768,GET,/shuttle/missions/sts-69/mission-sts-69.html,200.0,11264.0,1995-08-09 07:02:48
4,23,***.novo.dk,807951938,GET,/shuttle/countdown/liftoff.html,200.0,4665.0,1995-08-09 07:05:38

##6.Membuat Kolom pada session berdasarkan Host, Mengurutkan Berdasarkan Waktu, dan Menyimpan Tabel Final

In [ ]:
import pandas as pd
from IPython.display import display

# 1. Tentukan file input
file_name = "time_converted_NASA.csv"

# 2. Kolom penting
col_ip = "host"
col_time = "datetime_readable"
new_col_name = "SESSION"

print(f"Memuat data dari {file_name}...")
try:
    df = pd.read_csv(file_name, sep=';', parse_dates=[col_time])
except Exception as e:
    print("Gagal membaca file:", e)
    raise SystemExit()

# 3. Cek kolom
if col_ip not in df.columns or col_time not in df.columns:
    print("Kolom tidak ditemukan.")
    raise SystemExit()

# 4. Buat kolom SESSION berdasarkan IP
print("Membuat kolom SESSION berdasarkan host unik...")
df[new_col_name] = df[col_ip].astype("category").cat.codes + 1

# 5. Urutkan data
df_sorted = df.sort_values(by=[new_col_name, col_time])

# 6. Hapus kolom time jika ada
if "time" in df_sorted.columns:
    df_sorted = df_sorted.drop(columns=["time"])

# 7. Simpan hasil
output_filename = "session_data_full_NASA.csv"
df_sorted.to_csv(output_filename, index=False, sep=",")

print("\nBerhasil! Data sudah diproses.")
print("Preview dalam bentuk tabel:")

# 8. Tampilkan tabel rapi
preview_cols = [new_col_name, col_ip, col_time]
if "url" in df_sorted.columns:
    preview_cols.append("url")

display(df_sorted[preview_cols].head(10))

Memuat data dari time_converted_NASA.csv...
Membuat kolom SESSION berdasarkan host unik...

Berhasil! Data sudah diproses.
Preview dalam bentuk tabel:

,SESSION,host,datetime_readable,url
0,1,***.novo.dk,1995-07-11 12:17:09,/ksc.html
1,1,***.novo.dk,1995-07-11 12:17:48,/shuttle/missions/missions.html
2,1,***.novo.dk,1995-07-11 12:23:01,/shuttle/resources/orbiters/columbia.html
3,1,***.novo.dk,1995-08-09 07:02:48,/shuttle/missions/sts-69/mission-sts-69.html
4,1,***.novo.dk,1995-08-09 07:05:38,/shuttle/countdown/liftoff.html
5,1,***.novo.dk,1995-08-09 07:07:40,/shuttle/countdown/lps/fr.html
6,2,001.msy4.communique.net,1995-08-30 06:55:47,/software/winvn/winvn.html
7,3,007.thegap.com,1995-07-06 21:24:28,/shuttle/missions/sts-71/mission-sts-71.html
8,3,007.thegap.com,1995-07-06 21:28:35,/shuttle/missions/sts-71/mission-sts-71.html
9,3,007.thegap.com,1995-07-06 21:37:44,/shuttle/missions/sts-71/images/images.html

In [ ]:
import pandas as pd
from IPython.display import display  # Tambahan agar output tampil dalam kotak

# 1. Tentukan file input (file yang memiliki 'datetime_readable')
file_name = "time_converted_NASA.csv"

# 2. Tentukan kolom-kolom yang akan kita gunakan
col_ip = "host"                # Kolom untuk mengelompokkan sesi
col_time = "datetime_readable" # Kolom untuk mengurutkan sesi
new_col_name = "SESSION"       # Nama kolom sesi baru

print(f"Memuat data dari {file_name}...")
try:
    # 3. Muat dataset (pemisah asli adalah ';')
    df = pd.read_csv(file_name, sep=';', parse_dates=[col_time])
except FileNotFoundError:
    print(f"Error: File {file_name} tidak ditemukan.")
    print("Pastikan Anda sudah menjalankan skrip konversi 'time' sebelumnya.")
    exit()
except ValueError as e:
    print(f"Error saat membaca {file_name}. Cek kolom '{col_time}'.")
    print(f"Detail: {e}")
    exit()


# 4. Periksa apakah kolom yang diperlukan ada
if col_ip in df.columns and col_time in df.columns:

    # 5. BUAT KOLOM SESSION (Logika sama seperti sebelumnya)
    print(f"Membuat kolom '{new_col_name}' berdasarkan '{col_ip}' unik...")
    df[new_col_name] = df[col_ip].astype('category').cat.codes + 1

    # 6. Urutkan data berdasarkan SESSION dan WAKTU
    print(f"Mengurutkan data berdasarkan '{new_col_name}' dan '{col_time}'...")
    df_sorted = df.sort_values(by=[new_col_name, col_time], ascending=True)

    # 8. Kolom yang ingin dipertahankan
    columns_to_keep = ['SESSION', 'host', 'datetime_readable', 'url']

    print(f"\nMemfilter data untuk HANYA menyimpan kolom: {columns_to_keep}...")
    df_final_output = df_sorted[columns_to_keep].copy()

    # 9. Simpan DataFrame hasil akhir
    output_filename = "session_host_time_url_NASA.csv"

    print(f"Menyimpan data ke {output_filename} dengan pemisah KOMA (',')...")
    df_final_output.to_csv(output_filename, index=False, sep=',')

    print(f"\nBerhasil! File baru disimpan sebagai: {output_filename}.")
    print("\nPratinjau data baru (4 kolom):")

    # Tampilkan dalam kotak
    display(df_final_output.head())

else:
    print(f"Error: Kolom '{col_ip}' atau '{col_time}' tidak ditemukan di {file_name}.")

Memuat data dari time_converted_NASA.csv...
Membuat kolom 'SESSION' berdasarkan 'host' unik...
Mengurutkan data berdasarkan 'SESSION' dan 'datetime_readable'...

Memfilter data untuk HANYA menyimpan kolom: ['SESSION', 'host', 'datetime_readable', 'url']...
Menyimpan data ke session_host_time_url_NASA.csv dengan pemisah KOMA (',')...

Berhasil! File baru disimpan sebagai: session_host_time_url_NASA.csv.

Pratinjau data baru (4 kolom):

,SESSION,host,datetime_readable,url
0,1,***.novo.dk,1995-07-11 12:17:09,/ksc.html
1,1,***.novo.dk,1995-07-11 12:17:48,/shuttle/missions/missions.html
2,1,***.novo.dk,1995-07-11 12:23:01,/shuttle/resources/orbiters/columbia.html
3,1,***.novo.dk,1995-08-09 07:02:48,/shuttle/missions/sts-69/mission-sts-69.html
4,1,***.novo.dk,1995-08-09 07:05:38,/shuttle/countdown/liftoff.html

# CARA KE-2

##1.Membaca Dataset

In [ ]:
import pandas as pd

# Path dataset
file_path = "data.csv"

df = pd.read_csv(file_path, sep=';')

# Convert time
df["Timestamp"] = pd.to_datetime(df["time"], unit="s")

# Rename
df.rename(columns={"host": "Host"}, inplace=True)

df.head()

,Unnamed: 0,Host,time,method,url,response,bytes,Timestamp
0,0,***.novo.dk,805465029,GET,/ksc.html,200.0,7067.0,1995-07-11 12:17:09
1,1,***.novo.dk,805465031,GET,/images/ksclogo-medium.gif,200.0,5866.0,1995-07-11 12:17:11
2,2,***.novo.dk,805465051,GET,/images/MOSAIC-logosmall.gif,200.0,363.0,1995-07-11 12:17:31
3,3,***.novo.dk,805465053,GET,/images/USA-logosmall.gif,200.0,234.0,1995-07-11 12:17:33
4,4,***.novo.dk,805465054,GET,/images/NASA-logosmall.gif,200.0,786.0,1995-07-11 12:17:34

##2.Konversi URL Menjadi Label Huruf

In [ ]:
def num_to_letters(n):
    """Konversi angka ke huruf: 0→A, 1→B, ..., 25→Z, 26→AA, dst."""
    result = ""
    n += 1
    while n > 0:
        n -= 1
        result = chr(65 + (n % 26)) + result
        n //= 26
    return result

# --- Hasil Langsung ---
[num_to_letters(i) for i in range(10)]

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

##3.Pembentukan Web Usage Session

In [ ]:
def num_to_letters(n):
    string = ""
    while n >= 0:
        string = chr(n % 26 + ord('A')) + string
        n = n // 26 - 1
    return string

def process_web_usage(df):
    """
    Membentuk sesi web usage 20 menit per host.
    URL diganti dengan huruf A-Z.
    """

    # Buat mapping URL → huruf
    unique_urls = df["url"].unique() # Corrected 'URL' to 'url'
    url_map = {url: num_to_letters(i) for i, url in enumerate(unique_urls)}
    df["URL_Label"] = df["url"].map(url_map) # Corrected 'URL' to 'url'

    df = df.sort_values(by=["Host", "Timestamp"])

    results = []

    for host, group in df.groupby("Host"):
        group = group.sort_values("Timestamp").reset_index(drop=True)

        sessions = []
        cur_session = []
        prev_time = None

        for _, row in group.iterrows():
            ts = row["Timestamp"]
            label = row["URL_Label"]

            if prev_time is None:
                cur_session.append((ts, label))
            else:
                delta = (ts - prev_time).total_seconds() / 60

                # aturan sesi 20 menit
                if delta > 20:
                    sessions.append(cur_session)
                    cur_session = [(ts, label)]
                else:
                    cur_session.append((ts, label))

            prev_time = ts

        if cur_session:
            sessions.append(cur_session)

        results.append({
            "Host": host,
            "Sessions": sessions
        })

    return results, url_map


# --- Hasil Langsung ---
results, url_map = process_web_usage(df)
results[:1]   # tampilkan contoh 1 host pertama

[{'Host': '***.novo.dk',
  'Sessions': [[(Timestamp('1995-07-11 12:17:09'), 'A'),
    (Timestamp('1995-07-11 12:17:11'), 'B'),
    (Timestamp('1995-07-11 12:17:31'), 'C'),
    (Timestamp('1995-07-11 12:17:33'), 'D'),
    (Timestamp('1995-07-11 12:17:34'), 'E'),
    (Timestamp('1995-07-11 12:17:38'), 'F'),
    (Timestamp('1995-07-11 12:17:48'), 'G'),
    (Timestamp('1995-07-11 12:17:51'), 'H'),
    (Timestamp('1995-07-11 12:19:13'), 'I'),
    (Timestamp('1995-07-11 12:19:17'), 'E'),
    (Timestamp('1995-07-11 12:22:03'), 'J'),
    (Timestamp('1995-07-11 12:22:08'), 'K'),
    (Timestamp('1995-07-11 12:23:01'), 'L')],
   [(Timestamp('1995-08-09 07:02:48'), 'M'),
    (Timestamp('1995-08-09 07:02:55'), 'N'),
    (Timestamp('1995-08-09 07:03:02'), 'I'),
    (Timestamp('1995-08-09 07:03:06'), 'J'),
    (Timestamp('1995-08-09 07:03:12'), 'K'),
    (Timestamp('1995-08-09 07:03:52'), 'O'),
    (Timestamp('1995-08-09 07:04:08'), 'P'),
    (Timestamp('1995-08-09 07:04:24'), 'E'),
    (Timestamp('1995-08-09 07:05:07'), 'Q'),
    (Timestamp('1995-08-09 07:05:14'), 'R'),
    (Timestamp('1995-08-09 07:05:38'), 'S'),
    (Timestamp('1995-08-09 07:06:21'), 'T'),
    (Timestamp('1995-08-09 07:07:24'), 'U'),
    (Timestamp('1995-08-09 07:07:40'), 'V'),
    (Timestamp('1995-08-09 07:07:58'), 'W'),
    (Timestamp('1995-08-09 07:08:22'), 'X')]]}]

##4.Membentuk Tabel Web Usage (Host – Session – Timestamp – Page)

In [ ]:
url_mapping_df = pd.DataFrame([
    {"URL": url, "Label": label}
    for url, label in url_map.items()
])

url_mapping_df

                                                   URL Label
0                                            /ksc.html     A
1                           /images/ksclogo-medium.gif     B
2                         /images/MOSAIC-logosmall.gif     C
3                            /images/USA-logosmall.gif     D
4                           /images/NASA-logosmall.gif     E
..                                                 ...   ...
361                                  /finance/tour.gif    MX
362                              /finance/brrow_1t.gif    MY
363  /shuttle/missions/sts-71/images/KSC-95EC-0423.jpg    MZ
364         /software/winvn/faq/WINVNFAQ-Contents.html    NA
365                                                NaN    NB

[366 rows x 2 columns]

##5.Ringkasan Total Sesi Per Host

In [ ]:
table_rows = []

for item in results:
    host = item["Host"]
    sessions = item["Sessions"]

    for session_idx, session in enumerate(sessions, start=1):
        for ts, label in session:
            table_rows.append({
                "Host": host,
                "Session": session_idx,
                "Timestamp": ts,
                "Page": label
            })

usage_table = pd.DataFrame(table_rows)

usage_table

                 Host  Session           Timestamp Page
0         ***.novo.dk        1 1995-07-11 12:17:09    A
1         ***.novo.dk        1 1995-07-11 12:17:11    B
2         ***.novo.dk        1 1995-07-11 12:17:31    C
3         ***.novo.dk        1 1995-07-11 12:17:33    D
4         ***.novo.dk        1 1995-07-11 12:17:34    E
...               ...      ...                 ...  ...
103758  128.217.62.39       13 1995-08-15 19:24:49    A
103759  128.217.62.39       13 1995-08-15 19:24:50    B
103760  128.217.62.39       13 1995-08-15 19:24:51    C
103761  128.217.62.39       13 1995-08-15 19:24:51    E
103762  128.217.62.39       13 1995-08-15 19:24:51    D

[103763 rows x 4 columns]

In [ ]:
session_summary = usage_table.groupby("Host")["Session"].nunique().reset_index()
session_summary.rename(columns={"Session": "Total Sessions"}, inplace=True)

session_summary

                                 Host  Total Sessions
0                         ***.novo.dk               2
1             001.msy4.communique.net               1
2                      007.thegap.com               5
3     01-dynamic-c.wokingham.luna.net               6
4               01.ts01.zircon.net.au               1
...                               ...             ...
2246                    128.217.62.30               1
2247                    128.217.62.33               4
2248                    128.217.62.35               8
2249                    128.217.62.38              19
2250                    128.217.62.39              13

[2251 rows x 2 columns]

##6.MEMBANGUN TABEL BINARY PER HALAMAN

In [ ]:
# 5. MEMBANGUN TABEL BINARY PER HALAMAN (A=1, lainnya=0)

def build_binary_table(results, url_map):
    all_labels = sorted(url_map.values())  # A, B, C, ...
    rows = []

    for host_data in results:
        host = host_data["Host"]

        for session in host_data["Sessions"]:
            for ts, label in session:

                # buat baris kosong (semua 0)
                row = {l: 0 for l in all_labels}

                # halaman yang dikunjungi = 1
                row[label] = 1

                # tambahkan kolom lain
                row["Time"] = ts.strftime("%H:%M")
                row["Host"] = host

                rows.append(row)

    return pd.DataFrame(rows)


binary_table = build_binary_table(results, url_map)

print("=== Tabel Binary Halaman Dikunjungi ===")
display(binary_table.head(20))

# Simpan CSV bila diperlukan
binary_table.to_csv("binary_web_usage.csv", index=False)

=== Tabel Binary Halaman Dikunjungi ===

,A,AA,AB,AC,AD,AE,AF,AG,AH,AI,...,S,T,U,V,W,X,Y,Z,Time,Host
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,12:17,***.novo.dk
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,12:17,***.novo.dk
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,12:17,***.novo.dk
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,12:17,***.novo.dk
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,12:17,***.novo.dk
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,12:17,***.novo.dk
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,12:17,***.novo.dk
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,12:17,***.novo.dk
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,12:19,***.novo.dk
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,12:19,***.novo.dk
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,12:22,***.novo.dk
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,12:22,***.novo.dk
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,12:23,***.novo.dk
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,07:02,***.novo.dk
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,07:02,***.novo.dk
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,07:03,***.novo.dk
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,07:03,***.novo.dk
17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,07:03,***.novo.dk
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,07:03,***.novo.dk
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,07:04,***.novo.dk

In [ ]:
from openpyxl import Workbook

# Buat workbook baru
wb = Workbook()

# ----------------------------
# Sheet 1: URL Mapping
# ----------------------------
ws1 = wb.active
ws1.title = "URL Mapping"

# Header
ws1.append(list(url_mapping_df.columns))

# Isi data
for row in url_mapping_df.itertuples(index=False):
    ws1.append(list(row))

# ----------------------------
# Sheet 2: Web Usage Sessions
# ----------------------------
ws2 = wb.create_sheet("Web Usage Sessions")

ws2.append(list(usage_table.columns))
for row in usage_table.itertuples(index=False):
    ws2.append(list(row))

# ----------------------------
# Sheet 3: Session Summary
# ----------------------------
ws3 = wb.create_sheet("Session Summary")

ws3.append(list(session_summary.columns))
for row in session_summary.itertuples(index=False):
    ws3.append(list(row))

# ----------------------------
# Save file
# ----------------------------
output_path = "/content/web_usage_complete.xlsx"
wb.save(output_path)

print("✔ File Excel lengkap berhasil dibuat:")
print(output_path)

✔ File Excel lengkap berhasil dibuat:
/content/web_usage_complete.xlsx